### ISSUE TITLE
bug(clickhouse): settings in create_table not working as expected (I think)

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#10198]
I'm trying to create a `MATERIALIZED VIEW` on clickhouse  using raw_sql, and if I do 

```python
con.create_table(
        "my_table",
        {"id": [1, 2, 3], "val": ["a", "b", "c"]},
        overwrite=True,
        settings={"allow_nullable_key": "0"},
    )

con.raw_sql("""CREATE MATERIALIZED VIEW mat_view_example ENGINE=MergeTree() ORDER BY id AS SELECT * FROM my_table""")
```

I get an error (which I don't if I run this directly on the CLI)

```python-traceback
>       raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
E       clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://localhost:8123/ returned response code 400)
E        Code: 44. DB::Exception: Sorting key contains nullable columns, but merge tree setting `allow_nullable_key` is disabled. (ILLEGAL_COLUMN) (version 24.8.4.13 (official build))

/Users/naty/mambaforge/envs/ibis-dev/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py:377: DatabaseError
```

I put a breakpoint in `create_table` and inspected the sql it looks like 

```SQL
('CREATE OR REPLACE TABLE "my_table" ("id" Nullable(Int64), "val" '
 'Nullable(String)) ENGINE=MergeTree ORDER BY () SETTINGS allow_nullable_key = '
 '\'0\' AS SELECT * FROM "ibis_pandas_memtable_323oi2c7ezer7lnmzz7inwh4xe"')
```

which it already creates the columns as nullables and it looks like the `allow_nullable_key=0` is not having effect when executing the query. 

For the record, if I create the table like below, I can create the materialized view. 

```python 
 con.create_table(
        "my_table",
        {"id": [1, 2, 3], "val": ["a", "b", "c"]},
        schema=ibis.schema({"id": "!int", "val": "!str"}),
        overwrite=True,
    )
```

**Comment by cpcloud** [comment]
This is not a bug.

The error is coming from the creation of the `MATERIALIZED VIEW`, not from creating `my_table`. Try commenting out the `raw_sql` call and you'll see that `my_table` gets created successfully.

Also notice `ORDER BY ()`. The `()` indicates an empty tuple, in this case that means there are no ordering keys, so the `allow_nullable_key` will have no bearing here.

It **WILL** have an effect on the `MATERIALIZED VIEW` creation because you're explicitly specifying an `ORDER BY id` in the creation.
