### ISSUE TITLE
BUG: Memory leak with postgres backend

### ISSUE THREAD

**Issue by FedericoV** [ibis-project/ibis#1059]
I am downloading a big table from redshift (via the postgres driver) and saving it to disk.  The table is too big to fit into RAM, so I'm pulling it in chunks, and saving each chunk.

```
for i in tqdm.tqdm_notebook(range(n_iters)):
    dataset_chunk = model_with_prod2vec.limit(upper_bound, offset=lower_bound).execute()
    
    output_fn = os.path.join(output_dir, 'Model_Chunk_{}.csv'.format(n_chunk))
    with open(output_fn, 'wb') as output_fh:
        feather.write_dataframe(dataset_chunk, output_fh)
    
    lower_bound = upper_bound
    upper_bound += chunk_size
    n_chunk += 1
    
    del(dataset_chunk)
    gc.collect()
```

Without adding the last two lines the memory massively increased after each cycle eventually causing a crash.  Just adding gc.collect() did not seem to be sufficient - I had to delete the chunk first.  I'm guessing there are some references hanging in there that are not freed?

**Comment by FedericoV** [comment]
Spoke too soon: even with the last two lines, memory usage continues to increase during the loop.

**Comment by cpcloud** [comment]
@FedericoV Thanks for reporting. The memory leak here is probably due to a pandas DataFrame or Series hanging around longer than it's supposed to. I'll investigate and see if there's something we can do about this.

**Comment by cpcloud** [comment]
@FedericoV I looked into this and it *isn't* related to pandas (I was able to reproduce this without constructing a DataFrame). One of SQLAlchemy or psycopg2 is holding on to previous result sets instead of discarding them, moreover it appears to hold on to the memory from previous result sets, which leads to quadratic behavior. I hope I'm wrong or misinformed somehow about the last part. I'm going to explore this some more to try to get to the bottom of it and see if there's a way to fix it and worst case workaround it.

**Comment by FedericoV** [comment]
Hi Philip,

thanks so much for the help.  Let me know if there are some corner cases that you'd like me to test.

**Comment by cpcloud** [comment]
@FedericoV I think you might be misunderstanding the semantics of `limit`. The required argument is the number of rows to return and the optional `offset` argument is the row offset to start at. In Python slice syntax it would look like this:

```python
t[offset:offset + limit]
```

So, each time in the query you're increasing the result set size because you're increasing the value of `upper_bound` by `chunk_size` in each iteration of the loop, so the result set size is going to grow by `chunk_size` rows with every call to `execute`.

If you want `chunk_size` rows on every iteration, then your query should be

```python
table.limit(chunk_size, offset=lower_bound)
lower_bound += chunk_size
```

**Comment by cpcloud** [comment]
So, I don't think there's a memory leak here in ibis nor in any of the mentioned libraries.
