### ISSUE TITLE
SQL Parser

### ISSUE THREAD

**Issue by mrocklin** [ibis-project/ibis#1156]
Is SQL parsing within scope for Ibis?  

I've been asked a few times to support SQL queries with dask.dataframe.  This would require both SQL parsing and high-level query optimization, neither of which dask.dataframe is particularly well suited for.  Ibis seems like a natural place to focus query optimization efforts and, with the Pandas bindings I'm hoping that it would be somewhat straightforward to lower Ibis to dask.dataframe.  I'm not sure that this project wants to get into this game though.

cc @mariusvniekerk

**Comment by cpcloud** [comment]
There are many different flavors of SQL, each of which has a (sometimes drastically) different grammar, how do we decide which one(s) to support? We'd likely need a parser for each one for such a feature to be useful.

I would imagine that people want SQL support because it's costly to rewrite their queries in Dask or Ibis. If that's true, then I would also imagine that those queries are very specific to the underlying system otherwise it would probably be easy to rewrite it in Dask or Ibis. If *that's* true then supporting SQL parsing wouldn't be very useful unless we had parsers that could handle many of the syntactic idiosyncrasies of the system in question.

For the last reason, IMO it seems out of scope for Ibis.

@mrocklin Do you have any idea what kinds of queries people want to throw at Dask?

**Comment by wesm** [comment]
It would be possible to use Apache Calcite to handle query parsing and planning, but this would be quite a bit of work

**Comment by mrocklin** [comment]
> @mrocklin Do you have any idea what kinds of queries people want to throw at Dask?

I've gotten the sense that they want to point standard BI tools at it.  I honestly don't have much exposure to this space.  I suspect that @wesm has a better understanding here.  

@mariusvniekerk also mentioned Apache Calcite.  This is, I'm sure, a fair amount of work.  To be clear I'm not asking for anything here nor stating any intention to pursue work in this direction myself.  I'm just broaching the topic to see if there are any established thoughts.  Feel free to close.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/30479  PR to pandas for adding a sql parser, but i think more appropriate for a front-end to create an ibis expression

**Comment by zbrookle** [comment]
Just realized this issue was here, issue #2236 has a package listed in it that I've created to perform solve this issue, either as an internal parser or an external package listed in documentation

**Comment by zbrookle** [comment]
@jreback @mrocklin You can probably close this if you'd like with my package linked externally now
