### ISSUE TITLE
Getting started with Ibis on Redshift

### ISSUE THREAD

**Issue by CerebralMastication** [ibis-project/ibis#1223]
Hey team, kudos for hard work on Ibis. I've been trying to start using Ibis against a Redshift DB and the Postgres connectivity seems to work just dandy. However Ibis is not behaving as I would expect, which might be an issue with my expectations rather than Ibis. 

let me give you an example of my snag:

I set up a connection to redshift using ibis.sql.postgres.api.connect() and all looks good. 

Then I create some Ibis table objects:

```
ds = con.table('dimOfInterest')
fev = con.table('factOfInterest')
```
this works as expected and I can execute ds.info() for example and see info. So I then do a join:

`df = ds.inner_join(fev, ds.key == fev.key)
`
all's good... so I do a filter:

`df_filtered = df.filter( [df.snapshotname == 'MyName'] )
`
and that fails with `AttributeError: 'TableExpr' object has no attribute 'snapshotname'`

So I get the general idea that even though I have done a join to create df, somehow Ibis does not know what fields are in df. Yet I don't yet want to fetch all of df by doing a `df.execute()`. 

Q1: What am I missing here? Is there a way to combine multiple filter steps and accumulate them and then at the end have Ibis roll those all into one SQL statement and execute it? I think that is my expectation primarily because that's how dplyr works over in R land. Is my expectation wrong?

Interestingly, when I run df.execute() I get the following error: `RelationError: Joined tables have overlapping names: ['key', 'modelkey']`. Which is pointing out the obvious to me. Key is my joining field, so it better be in both tables! And modelkey is, indeed, redundant in naming, but I'm surprised that this is a problem since in Pandas I don't recall redundant names borking a join. 

Q2: How does one avoid redundant naming? Am I going to have to explicitly list which fields to keep? That begins to feel a lot like just writing SQL and is the sort of thing I had hoped to avoid in Ibis-land. 

I have read the documentation about [Ibis for SQL Programmers](http://docs.ibis-project.org/sql.html) and it illustrates multiple times the use of `ibis.impala.compile()` which no longer seems to be the location of this function. I looked around and I can't seem to find where that now lives. 

Q3: What's the modern incarnation of `ibis.impala.compile()`? I'm using Ibis 0.12.0.

Thank you all for your hard work and for handholding a newbie a bit!

**Comment by cpcloud** [comment]
@CerebralMastication Thanks for raising an issue!

Q1/Q2:
---

If there are overlapping column names then in general it's not possible to disambiguate the columns on their names alone.

This applies to join keys as well.

There's only one case where the value of all the key columns in a join is not ambiguous and it would make sense to choose one and that case is *inner joins where the join comparison operation is equality*:

```sql
left INNER JOIN right
  ON left.key1 = right.key1 AND left.key2 = right.key2 AND ... AND left.keyN = right.keyN
```

Every other `(join type, comparison operation)` pair can generate left and right key columns whose values may not be equivalent.

Here's an example where there's interesting information in the right key coming out of a left join, that you lose if you make a choice about which key to return (using PostgreSQL):

```
test=# create table a (key text); create table b (like a);
CREATE TABLE
CREATE TABLE

test=# insert into a values ('d'), ('d'), ('e'), ('f');
INSERT 0 4

test=# insert into b values ('d'), (null), ('f'), ('g');
INSERT 0 4

test=# select a.key as a_key, b.key as b_key from a left outer join b using (key);
 a_key | b_key 
-------+-------
 d     | d
 d     | d
 e     | 
 f     | f
(4 rows)
```

That said, of course you can still continue to perform operations on ibis expressions after a join, you need to project out the column names you want:

Using your example:

```python
ds = con.table('dimOfInterest')
fev = con.table('factOfInterest')
df = ds.inner_join(fev, ds.key == fev.key)
df = df[ds, fev.shapshotname]  # columns or other relations 
df_filtered = df.filter( [df.snapshotname == 'MyName'] )
```

> I'm surprised that this is a problem since in Pandas I don't recall redundant names borking a join

If you have overlapping key names, pandas makes a choice regarding which one of the same named join keys to return, and you can't easily make it do something different. Version 0.17.0 has the `indicator` flag, which tells you whether the value was in both or only in the left or right table but ibis has no need for such a flag since it knows exactly which tables every expression comes from. This does place a small burden on the user to be more explicit about which columns they want to use.

I'm open to adding the suffixes behavior that pandas has for overlapping columns, but that would have to include adding suffixes for join keys as well.

I'm also open to adding API(s) that make it convenient to tell ibis what the preferred behavior is on a per expression basis.

Q3
---

To get access to `ibis.impala.compile()` you need to install the dependencies for the impala backend. You can do this with:

```sh
pip install ibis-framework[impala]
```
in bash, or

```sh
pip install ibis-framework\[impala\]
```
in zsh.
