### ISSUE TITLE
Type of GroupedTableExpr is not Expr

### ISSUE THREAD

**Issue by collinwo** [ibis-project/ibis#1245]
Is it expected?
I will get error when pass a groupExpr into analysis.find_source_table()

IbisTypeError: 'op' is not a field in...

**Comment by cpcloud** [comment]
@collinwo What exactly are you trying to do with `GroupedTableExpr`? Are you encountering this bug during "normal" ibis operations?

Happy to try to enable whatever your use case is.

The objects in `ibis/expr/groupby.py` aren't full fledged expressions, and are really just spoofing the API of actual expressions so that they are useful intermediate objects on the way to actual expressions. For example,

```python
t = ibis.table([('a', 'int64'), ('b', 'string')])
g = t.groupby('b')  # this is only useful for calling methods to create an actual table/column/scalar expression, i.e., a means to an end, not an end state in itself
agged = g.aggregate(a_sum=lambda t: t.a.sum())  # possible end state

**Comment by collinwo** [comment]
I am trying to find the backend(e.g. resolve the PandasTable from a expr) from a expr, which the expr may contain GroupedTableExpr. So, I use analysis.find_source_table() to do it.  E.g

import ibis
from ibis.pandas import core, client
t = ibis.table([('a', 'int64'), ('b', 'string')])
g = t.groupby('b')
agged = g.aggregate(a_sum=lambda t: t.a.sum())
core.find_data(g)


BTW, I am developing a plugin that allows user to use ibis to query "our internal database"

**Comment by cpcloud** [comment]
@collinwo Sweet! I think you're looking for `ibis.client.find_backends`. That will yield all instances of `ibis.client.Client` depth-first.

**Comment by collinwo** [comment]
Great. Thx! Feel free to close the issue.
