### ISSUE TITLE
Invalid query generated after series of filters/mutates

### ISSUE THREAD

**Issue by seibs** [ibis-project/ibis#1496]
When a series of mutates/filters are moved to "WITH" statements, the compiled statement sometimes includes incorrect table references.

**Expression**
```
t = ibis.table([('file_date', 'timestamp'), ('PARTITIONTIME', 'date'), ('val', 'int64')])
def test(table):
    table = table[table.PARTITIONTIME < ibis.date('2017-01-01')]
    table = table.mutate(file_date=table.file_date.cast('date'))
    table = table[table.file_date < ibis.date('2017-01-01')]
    table[table]
    table = table.mutate(XYZ=table.val * 2)
    return table
x = test(t)
print(ibis.bigquery.compile(x.join(x.view())[x]))
```

**Compiled**
```
WITH t0 AS (
  SELECT *
  FROM t4
  WHERE `PARTITIONTIME` < '2017-01-01'
),
t1 AS (
  SELECT CAST(`file_date` AS DATE) AS `file_date`, `PARTITIONTIME`, `val`
  FROM t0
),
t2 AS (
  SELECT t1.*, t0.`val` * 2 AS `XYZ`
  FROM t1
  WHERE t1.`file_date` < '2017-01-01'
)
SELECT t2.*
FROM t2
  CROSS JOIN t2 t3
```

**Comment by seibs** [comment]
@cpcloud Sorry, the issue is a little hidden.  In the `t2` definition, the `t0` in the select should be `t1`.

**Comment by cpcloud** [comment]
@seibs Finally got around to fixing this. The issue here is that we're fusing across projections without considering the immediate parent table. What happens is that when we're looking for fusion opportunities in a project we look for common expressions in the deepest base table in the tree and assume that we can substitute in the matching columns from that in whatever query we're projecting. This is invalid because there may be other non-fused relations in between. For now, the fix is to only allow fusing with the immediate parent.
