### ISSUE TITLE
GROUP BY in the BigQuery backend

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis#1563]
I'm still learning Ibis, so I may be doing something wrong. I didn't find any examples of `group_by()` / `aggregate(by=...)` in the BigQuery tests.

```
import ibis

conn = ibis.bigquery.connect(
    project_id=YOUR_PROJECT_ID,
    dataset_id='bigquery-public-data.stackoverflow')
table = conn.table('posts_questions')
projection = table[['creation_date']]
projection = projection.mutate(year=projection.creation_date.year())

expression = projection.aggregate(
    [projection.count()],
    by=[projection.year])
print(expression.compile())
```

This prints the following SQL:
```
SELECT `year`, count(*) AS `count`
FROM (
  SELECT `creation_date`, EXTRACT(year from `creation_date`) AS `year`
  FROM `bigquery-public-data.stackoverflow.posts_questions`
) t0
GROUP BY 1
```

I'd have expected `GROUP BY year` rather than `GROUP BY 1`. If "group by" isn't supported or it couldn't find the "year" column for some reason, I would have expected an error.

**Comment by cpcloud** [comment]
@tswast The `GROUP BY 1` syntax is valid BigQuery SQL.

```
In [4]: conn = ibis.bigquery.connect(YOUR_PROJECT_ID, 'bigquery-public-data.stackoverflow')

In [5]: table = conn.table('posts_questions')

In [6]: projection = table[['creation_date']]

In [7]: projection = projection.mutate(year=projection.creation_date.year())

In [8]: expression = projection.aggregate([projection.count()], by=[projection.year])

In [9]: result = expression.execute()

In [10]: result
Out[10]:
    year    count
0   2013  2060753
1   2018   997508
2   2012  1645498
3   2017  2318405
4   2011  1200601
5   2009   343879
6   2014  2164895
7   2010   694410
8   2015  2219791
9   2016  2226478
10  2008    58399
```

Ibis generates code this way to avoid repeated the `GROUP BY` key if the key is a non-trivial expression. If you rewrite your expression to directly compute the `year` grouping key rather than computing it in subquery first you can see what I'm talking about:

```
In [25]: expr = table.aggregate(numrows=table.count(),
    ...:                        by=table.creation_date.year().name('year_created'))
    ...:

In [26]: print(expr.compile())
SELECT EXTRACT(year from `creation_date`) AS `year_created`,
       count(*) AS `numrows`
FROM `bigquery-public-data.stackoverflow.posts_questions`
GROUP BY 1
```

If we put the whole expression into the compiled output, it becomes more difficult to read:

```sql
SELECT EXTRACT(year from `creation_date`) AS `year_created`,
       count(*) AS `numrows`
FROM `bigquery-public-data.stackoverflow.posts_questions`
GROUP BY EXTRACT(year from `creation_date`)
```
And that's just with one grouping key!

I don't think there's a database that ibis supports that does not accept the `1` syntax.

One alternative might be to use the name of the grouping key instead, if it's an expression. I vaguely remember some databases that support the `1` syntax do *not* support using the name of a group by key expression, but I could be mistaken there.

**Comment by tswast** [comment]
Thanks for the explanation! I didn’t realize 1 in this context refers to the first column in the select. I always repeated the expression or used the column name when writing SQL by hand. I’ll close this issue as working-as-intended.
