### ISSUE TITLE
Dremio support

### ISSUE THREAD

**Issue by Posnet** [ibis-project/ibis#1769]
I am interested in adding Dremio support to ibis.

However it is not clear to me which is the best way to do this.

Dremio is accessed via ODBC or JDBC so I was planning to use ODBC w/ pyodbc or turbodbc (though I did notice someone is already working on this #999)
It is SQL based but I'm not sure if it should go in the sql subdirectory or have it's own root directory like impala/bigquery/clickhouse. 
Is it appropriate to just copy one of the existing directories (i.e. impala) and modify all the compile.py functions where the syntax between the SQL dialects differs? or is these a more generic way using the structure from the sql directory.
I'd like to support the Dremio specific functionality such as virtual tables/dataset creation and accelerations, some of which can only be modified by their HTTP API and not directly though SQL. Does it make sense to have that functionality in Ibis or is it not planned to support non-SQL operations. 

Thanks.

Alec

**Comment by cpcloud** [comment]
We'd love to have support for Dremio!

The `sql` subdirectory is for `sqlalchemy`-based backends. If there's a SQLAlchemy API for Dremio then you could use that and look at the other backends under `sql` for examples of what to do.

If you're implementing a string-based backend then yes, looking at impala/bigquery/clickhouse/mapd would be the way to go. You probably don't want to do a full copy paste, since you could ostensibly reuse some of the code from the "closest" existing backend.

In any event, happy to discuss more as needed.

**Comment by cpcloud** [comment]
Creation of tables is definitely something that should be in ibis, and if there are clean mappings from Dremio concepts to SQL concepts then those can live in ibis as well.

**Comment by cpcloud** [comment]
Will happily accept PRs.
