### ISSUE TITLE
Lint failing in Windows Azure pipelines

### ISSUE THREAD

**Issue by scottcode** [ibis-project/ibis#1897]
All the Azure pipelines for Windows Python 3.6 and 3.7 have been failing recently at the `Lint` step, regardless of whose pull request it is. The error/log doesn't give any indication of what happened, and when I run the linter locally it passes. 

Since it is only two of the Windows environments and not the Windows Python 3.5 one, I wonder if it has something to do with the environment configuration. If you look at the "Agent" for each of the Windows pipelines, they differ along the lines of 3.5 vs 3.6 + 3.7. You can see it by clicking on a specific build and the environment. It seems that the linter is failing only in the Windows 2019 environment. 

I've copied the environment breakdown below:

WindowsTest py35
Agent: Hosted Agent

WindowsTest py36
Agent: Hosted Windows 2019 with VS2019 2

WindowsTest py37
Agent: Hosted Windows 2019 with VS2019 3

**Comment by cpcloud** [comment]
All of the pipelines are using the same vm image. See https://github.com/ibis-project/ibis/blob/master/azure-pipelines.yml#L11, which is used here: https://github.com/ibis-project/ibis/blob/master/ci/azure/windows.yml#L9.

I don't think it's the VM image, since they are all the same. The python 3.5 environment is created using a different version of conda from 3.6/3.7 so something there might explain it.

**Comment by scottcode** [comment]
@cpcloud I see that you removed linting from Windows in #1896. That's reasonable, because it still gets done in the Linux environments. I don't think there's a concern about linting behaving differently between OSs. I'll close this, but feel free to re-open it if you feel like linting should be re-added later and want to keep a reminder.

**Comment by cpcloud** [comment]
Thanks!
