### ISSUE TITLE
[CI] BigQuery backend isn't be checked in PRs

### ISSUE THREAD

**Issue by anmyachev** [ibis-project/ibis#2067]
```
steps:
    - bash: |
        if [ -n "${GCLOUD_SERVICE_KEY}" ]; then
          mkdir -p /tmp/ibis
          base64 --decode --ignore-garbage <<< "${GCLOUD_SERVICE_KEY}" > /tmp/ibis/gcloud-service-key.json
        fi
      env:
        GCLOUD_SERVICE_KEY: $(GCLOUD_SERVICE_KEY)
      displayName: 'Setup BigQuery credentials'
      condition: eq(variables['System.PullRequest.IsFork'], 'False')
```

The main problem is that `GCLOUD_SERVICE_KEY` var define only for master branch.

Is it possible define the var for PRs?
Or is there a better solution?

@cpcloud @xmnlab

**Comment by jreback** [comment]
this *was* working before? and just recently broke?

**Comment by anmyachev** [comment]
The backend has not been checked in the PRs for 8 months (only checked on the wizard). The tests of this backend started to fall already at least from #2034 (most likely from #2044 but the CI build was not preserved)

Most likely, the tests started to fall after this BigQuery update:
https://github.com/googleapis/google-cloud-python/tree/bigquery-1.23.0

**Comment by icexelloss** [comment]
I looked at this yesterday. And noted, there are two orthogonal issues:
(1) BigQuery is not run as part of PullRequest CI
(2) BigQuery CI is broken

I not sure what's going on with (1) but for (2) I think it's because the newer version of bigquery library requires a higher version of PyArrow then we currently have (0.13). And we are not able to upgrade to PyArrow > 0.13 because pymapd https://github.com/omnisci/pymapd/blob/master/setup.py#L16

**Comment by icexelloss** [comment]
I think maybe for now we should ping BigQuery to a lower version to get the CI to pass and in the meantime work with pymapd folks to lift the PyArrow version ping from their side.

**Comment by icexelloss** [comment]
Pymapd issue: https://github.com/omnisci/pymapd/issues/292

**Comment by jreback** [comment]
sounds reasonable

**Comment by tswast** [comment]
Fixed by https://github.com/ibis-project/ibis-bigquery/pull/1, which uses GitHub Action `pull_request_target` (which has access to secrets) and a `run-ci` label to only run this workflow after it has been manually validated by a maintainer.

Regarding PyArrow versioning, hopefully with the repo split the BigQuery backend can accept a wider range of PyArrow versions and not be blocked by pymapd.
