### ISSUE TITLE
ImpalaClient.close() function doesn't work

### ISSUE THREAD

**Issue by xyliutw** [ibis-project/ibis#2215]
All,

After creating a connection to HDFS/Impala and do the function exists_table(), I usually use close() to clean all connecting session. But I noticed that if I close the connection first, the function create_table() still works. It means the function ImpalaClient.close() doesn't work and the connecting session will be stored in the pool. How do I clear these connections indeed?

Thanks,

Eric
```
import ibis

hdfs = ibis.hdfs_connect(host=localhost, port=9870)
client = ibis.impala.connect(host=localhost, port=21050, database='demo_db', timeout=45, hdfs_client=hdfs)

client.close()

schema = ibis.schema([('foo', 'string'),
                      ('year', 'int32'),
                      ('month', 'int16')])
name = 'new_table'
client.create_table(name, schema=schema, partition=['year', 'month'])
print(client.exists_table("new_table"))

```
```
>>> True
```

**Comment by cpcloud** [comment]
Is this still a problem?

**Comment by cpcloud** [comment]
@Andromelus Thanks for chiming in!

The impala backend uses a sqlalchemy connection pool ([`QueuePool`](https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.QueuePool) in particular).

There are a couple of facts to note here:

1. Calling `client.close()` calls the `dispose()` method of the connection pool which closes all **checked-in** connections. If any existing connection is checked **out** of the pool that connection will not be closed.
2. Even if all connections are checked in and you've called `client.close()`, you can still "resurrect" the pool by calling `con.raw_sql(...)` because that calls `client.pool.connect()` which will create a new connection.

Can you describe your use case in more detail?

**Comment by cpcloud** [comment]
@Andromelus Thanks for following up! It's extremely useful for us to get your feedback, so please keep asking questions when you have them.
