### ISSUE TITLE
ENH: Dask backend

### ISSUE THREAD

**Issue by zbrookle** [ibis-project/ibis#2245]
Are there any plan to create a dask backend? I imagine the implementation would be near identical to the pandas one that already exists

**Comment by jreback** [comment]
would surely take this, and agree its pretty darn straightforward to do.

**Comment by goodwanghan** [comment]
Hey, can you also add the support for Ray (modin?) and Rapids AI? I think they are all similar

**Comment by acivitillo** [comment]
One difference between pandas and dask is that in dask you can build a computational graph programmatically. We use this pattern to create an extract graph to run ETL jobs from various backends (Redshift, Salesforce, etc.). We define the columns and other attributes in a .json and then pass that to an Extract() to generate and submit the graph to a cluster. Since we are planning to support various enterprise backends, we use Arrow to store data in memory before sending it to Parquet over S3.

**Comment by cpcloud** [comment]
This exists.
