### ISSUE TITLE
feat: add cast as category support for sql backends

### ISSUE THREAD

**Issue by zbrookle** [ibis-project/ibis#2286]
I just made a pull request for adding this to the pandas backend, I'm fairly certain that category isn't a data type in any sql dialects, but this is just a note to check if those need to be added and to add them if they do. For reference, in code this is just support for 

```python
column.cast("category")
```

**Comment by cpcloud** [comment]
What would this do? Can you clarify what the semantics of this are?

**Comment by cpcloud** [comment]
Sounds like there's not much interest.

**Comment by cpcloud** [comment]
It's not clear what the future of `category` is in ibis. It sits at a lower level of abstraction because it's a way of representing another type. A string for example, can be `category`-ized or not, but the notion of a string is abstract over such representations. That kind physical layout visibility doesn't work well with basically anything in ibis.
