### ISSUE TITLE
DOC,BUG: ibis-project.org is 404'ing, broken links, HTTPS, Read the docs?

### ISSUE THREAD

**Issue by westurner** [ibis-project/ibis#2290]
http://ibis-project.org/ is 404'ing

https://docs.ibis-project.org/

**Comment by joosbuijsNL** [comment]
Seems to work again! :D

**Comment by westurner** [comment]
I suppose I'll leave this open pending an explanation?

**Comment by westurner** [comment]
A new sitemap.xml (and stable, versioned URLs) might be helpful for search results:

- https://www.google.com/search?q=ibis+dask
  - https://docs.ibis-project.org/roadmap.html -> 404

ReadTheDocs generates sitemaps, HTTPS redirection, custom domains, does stable versioned URLs, etc
https://readthedocs.org/

**Comment by jreback** [comment]
@datapythonista was updating how we build the docs, so this is all patched now.

**Comment by datapythonista** [comment]
Thanks for the heads up @westurner. We changed the domain from docs.ibis-project.org to ibis-project.org, and the CNAME file in the GitHub pages repo was being overwritten from a template in a repo that was not maintained, and we couldn't change. That part has been refactored in #2291, #2292 and #2293. Now all the files for publishing the website are in this repo, and that won't happen again. But the website was broken for several hours because of this.

**Comment by westurner** [comment]
What about HTTPS and HSTS support? (And serving past versions of the docs?)

"HTTPS for Custom Domains"
https://blog.readthedocs.com/https-for-custom-domains/

"Optional HSTS support"
https://github.com/readthedocs/readthedocs.org/issues/4135

...

"Custom domains on GitHub Pages gain support for HTTPS" 
https://github.blog/2018-05-01-github-pages-custom-domains-https/

https://github.com/ammaraskar/sphinx-action ::
> Github action that builds docs using sphinx and places errors inline

Is there an existing workflow for serving multiple pinned tags of the docs and a latest/ redirect RTD-style but with GitHub Pages?
