### ISSUE TITLE
DOC: Add information on why we have two Spark backends

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2775]
We currently have a spark and a pyspark backend. The pyspark backends depends on the spark one, but both seem to be using pyspark.

It's not clear to me (and I guess it's not to users) why we have the two backends, and when one should be used or the other. I think we should provide this information in https://ibis-project.org/docs/backends/spark.html

@icexelloss @timothydijamco do you think you can take care of this?

**Comment by datapythonista** [comment]
@icexelloss @timothydijamco I'm happy to take care of this in the docs, but do you mind adding a comment here, so I know what's the reason for the two backends (which I don't now). Thanks!

**Comment by icexelloss** [comment]
@datapythonista Good question. 

Historically, the "Spark" backend is first implemented because it's easy to hook in the existing SQL complication. Later on, we implemented the "PySpark" backend based on the PySpark API rather than the SQL statement and switch our internal application to use the PySpark backend. I have thought about deleting the Spark backend but kind of forgot about it.

Since we are doing a refactoring now anyway, might be a good time to delete it and keep only the PySpark one. Alternatively, we can just mark it as deprecated and remove in future version.

**Comment by datapythonista** [comment]
Thanks for the information, that's very useful to know.

I think we can start by removing the spark one from the docs, and maybe adding a deprecation warning when it's loaded (or remove it from the entrypoints so it's not available). Then we can remove it, I don't think it's a lot of work, but the pyspark depends on the spark one, so it's not immediate.

@jreback thought on this?

**Comment by jreback** [comment]
i would just remove it entirely unless we think there is value there

**Comment by datapythonista** [comment]
> i would just remove it entirely unless we think there is value there

Cool, thanks. I'll have a look and see if it can be done quickly. If it requires a decent amount of time I'll remove it from the entrypoints and docs, and leave removing the code to after the release.
