### ISSUE TITLE
chore(dev-deps): locally reproducible builds

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#2795]
Is there an easy way to locally reproduce the CI builds?

If I recall correctly ibis used to have a docker-compose configuration, but I can't find it anymore.

**Comment by datapythonista** [comment]
We don't have the docker-compose configuration anymore.  If you want to start a docker, you can get the parameters from the CI, and caller docker with them. For example, for postgres you've got the name of the image and the parameters to use in here https://github.com/ibis-project/ibis/blob/master/.github/workflows/main.yml#L62

**Comment by datapythonista** [comment]
The previous system, running Ibis itself in a docker image was making things very complex. Having a docker-compose file for the backends that need one seems reasonable. The only thing I don't like is that tings will be duplicated with the CI (which is way simpler if we use GitHub actions services for docker images, instead of our own).

I'm not sure if it's your case, but I'd assume most developers of Ibis care about one, or a small subset of backends. Does it make sense that you've got your own docker-compose with the backends that you care, instead of having to maintain a docker-compose file with all the backends in the repo? IMHO all you want is a shortcut for a long docker call, so keeping this out of the repo makes sense to me. Does it make sense to you?

**Comment by kszucs** [comment]
> The previous system, running Ibis itself in a docker image was making things very complex. Having a docker-compose file for the backends that need one seems reasonable. The only thing I don't like is that tings will be duplicated with the CI (which is way simpler if we use GitHub actions services for docker images, instead of our own).

The service definitions in GHA are almost identical to a docker-compose configuration while the latter would allow to spin up the same services both locally and GHA without code duplication.
It would be nice to be able to spin up the backends I'm interested in locally with a single command, including the testing data (this could be reused on CI to reduce maintenance cost). Something like:

```
ci/start_backends.sh mysql clickhouse  # perhaps this could be implemented in setup_env.sh
PYTEST_BACKENDS="mysql clickhouse" ci/run_tests.sh
```

> I'm not sure if it's your case, but I'd assume most developers of Ibis care about one, or a small subset of backends. 

I have plans for implementing new backends which may involve some refactoring as well eventually affecting multiple backends. 

> Does it make sense that you've got your own docker-compose with the backends that you care, instead of having to maintain a docker-compose file with all the backends in the repo? IMHO all you want is a shortcut for a long docker call, so keeping this out of the repo makes sense to me. Does it make sense to you?

Sure, I can keep it locally though I think it would make sense to have it upstream.

**Comment by datapythonista** [comment]
I see two main ways to address this, that don't cause all the problems of the previous containers:
- Stop using the GitHub Actions services, and instead have a docker-compose file and call docker-compose up in the CI (not sure why a `start_backends.sh` would be useful.
- Write a simple script that parses the GitHub actions services and generates a docker compose file. So, there is no duplication to maintain, and anyone interested in docker-compose can easily have the file locally

I'm happy to take a PR for any of the two approaches, as far as they keep things simple to understand and maintain.

> I have plans for implementing new backends which may involve some refactoring as well, eventually affecting multiple backends.

I'm working on some major refactoring of the backends API. I think it'd be useful to coordinate on this if you don't want to have to update your backends as I make progress on the refactoring and clean up.

**Comment by kszucs** [comment]
> * Stop using the GitHub Actions services, and instead have a docker-compose file and call `docker-compose up` in the CI 

Yes, that is my original idea. 

> * Write a simple script that parses the GitHub actions services and generates a docker compose file. So, there is no duplication to maintain, and anyone interested in docker-compose can easily have the file locally

This sounds more complicated.

> I'm working on some major refactoring of the backends API. I think it'd be useful to coordinate on this if you don't want to have to update your backends as I make progress on the refactoring and clean up.

I've seen that there are multiple PRs and issues targeting the backends API refactor. 
I wanted to ask you about the right approach since there are many moving parts at the moment. Any idea how to proceed?

**Comment by datapythonista** [comment]
> This sounds more complicated.

Agree in theory. But GitHub actions manages containers really nicely. If we want to run them  from docker-container ourselves, we may need to implement a way to detect when the container is ready (done automatically now by GA), and not sure if something else.I think that was done with a waiter container, which feels more like a hack to me, and adds a significant amount of complexity. If that's the case, a 10 lines script that parses a yaml from GA and generates a docker compose one, seems like a simpler option to me.

In any case, feel free to give it a try, and we can discuss in practice.


> I've seen that there are multiple PRs and issues targeting the backends API refactor.
> I wanted to ask you about the right approach since there are many moving parts at the moment. Any idea how/where to discuss?

Not sure if it's the answer that you want, but what makes sense to me is:
- SQL baseds should be implemented using SQLAlchemy. Feels like the Ibis engine used by Impala, Clickhouse, Bigquery is just reinventing the wheel. I think there are historical reasons for the way things are, but for new backends I think it makes more sense to implement a SQLAlchemy engine first, and then should be trivial to have it working in Ibis (particularly after the refactoring).
- I think at the moment is better to wait few more weeks. It's being tricky to get tests passing for the refactoring, but once those PRs are merged, I'll be able to follow up with easier ones that will delete a lot of repetitive code. Also, I'll start creating an ABC for a `Connection` class that will replace the `Client` and `Backend` ones. When that is done, implementing a backend should be way easier, since you'll have the spec of what's required (and eventually what's optional).

Does this make sense?

What are the backends that you are planning to implement?

**Comment by datapythonista** [comment]
Another option that probably makes even more sense is to create a Dockerfile per backend, which contains not only all the settings, but also the code in `ci/datamgr.py`. Using clickhouse as an example:

Currently, if you want to launch a clickhouse insance to test with Ibis, it's as simple as calling `docker run -p 8123:8123 -p 9000:9000 yandex/clickhouse-server:18.14`

With docker-compise, you can make it slightly shorter, `docker-compose up ibis-clickhouse`

But in both cases, after starting the docker, you need to doenload the data (+200Mb if I'm not wrong) with `ci/datamgr.py download`, and then load it into the container with `ci/datamgr.py clickhouse`.

If instead, we create a `Dockerfile` with the published ports, and also with the data downloading and loading, to run it locally would be as easy as `docker pull ibis-clickhouse && docker run ibis-clickhouse`. That would also speed up the CI a bit, since we're loading the data each time.

**Comment by kszucs** [comment]
> If instead, we create a `Dockerfile` with the published ports, and also with the data downloading and loading, to run it locally would be as easy as `docker pull ibis-clickhouse && docker run ibis-clickhouse`. That would also speed up the CI a bit, since we're loading the data each time.

That's entirely possible, we just need to define the dockerignore file precisely to have the right cache hits during docker build. We should also define a couple of other docker [flags](https://github.com/apache/arrow/blob/master/.env#L32-L34)) so we can reuse the built images across different hosts.

**Comment by kszucs** [comment]
> > This sounds more complicated.
> 
> Agree in theory. But GitHub actions manages containers really nicely. If we want to run them from docker-container ourselves, we may need to implement a way to detect when the container is ready (done automatically now by GA), and not sure if something else.I think that was done with a waiter container, which feels more like a hack to me, and adds a significant amount of complexity. If that's the case, a 10 lines script that parses a yaml from GA and generates a docker compose one, seems like a simpler option to me.
> 
> In any case, feel free to give it a try, and we can discuss in practice.

Sounds good to me.

> What are the backends that you are planning to implement?

I'm moving the backend related discussion to #2798 so we can focus on the docker-compose setup in this issue.

**Comment by Lunaticus7** [comment]
I'm trying to use https://github.com/nektos/act for running GA locally(haven't succeeded) and `setup_env.sh` costs lots of time in conda and download each time.

> If instead, we create a Dockerfile with the published ports, and also with the data downloading and loading, to run it locally would be as easy as docker pull ibis-clickhouse && docker run ibis-clickhouse. That would also speed up the CI a bit, since we're loading the data each time.

This sounds like an easier way to me. Can `act`  do the same thing, maybe ?

**Comment by cpcloud** [comment]
The `docker-compose.yml` file is back, and the CI became simpler because of it. https://github.com/ibis-project/ibis/pull/3323.
