### ISSUE TITLE
Extending TableExpr/TableNodes

### ISSUE THREAD

**Issue by saschahofmann** [ibis-project/ibis#2806]
As described in [this issue in the BigQuery repo](https://github.com/ibis-project/ibis-bigquery/issues/58#issuecomment-853150049), I am trying to register the new pivot functionality to our Ibis project. 

After spending some time on the whole registry issue, I am now pretty confident that this won't work with neither `compiles` nor `add_operation`. 

So my question is, can I (easily) extend the TableNode/TableExpr, similar to how I would register functions to Columns? 

The only thing I can come up with is to monkeypatch `BigQueryQueryBuilder`, not sure I want to go there!

**Comment by saschahofmann** [comment]
@datapythonista could you help me out here?

**Comment by datapythonista** [comment]
Not sure I fully understand the problem. First, I think you should be using `master`, since that part of the code changed significantly, and it's going to change even more after #2818 is finished and merged.

Then, `compiles` and `add_operation` are just syntactic sugar, and they shouldn't be used in Ibis or backend code, only `add_operation` should be used, and only in user code.

The relevant part is that the `BigQueryExprTranslator.operation_registry` dictionary has the entry with the Ibis operation as key, and the function as value. I'm not sure about this particular case, since `PIVOT` is kind of a special functionality, and not an operation. Not sure exactly where it belongs, but seems to be a top level keyword (like `FROM`, `WHERE`, `GROUP BY`...). I don't think those are supported by Ibis. I think this should be implemented in the query builder (soon renamed as compiler). I don't think you need to monkeypatch it, since you're already subclassing it. You need to just overwrite some methods that are not usually overwritten.

What is worth considering, is that I think we should move in the direction of using SQLAlchemy for BigQuery, see https://github.com/ibis-project/ibis-bigquery/issues/72. Not sure if `PIVOT` is supported there, you can have a look. But depending on how much work this change implies, it may not be worth to implement at this point.

**Comment by saschahofmann** [comment]
Yeah, I don't think this will make it into ibis, but I would think that it should be possible to use something like `add_operation ` when using the library as a user. SQLAlchemy doesn't support pivot and I doubt it will in the future. In the end, this is a functionality only supported by a few databases. 

My point here is, that it seems like I am not able to add an operation to a `TableExpr` instead of e.g. a `StringValue`. As you said I probably need to overwrite the QueryBuilder. Because I don't intend to do it internally, I was thinking about monkeypatching it. Does that make sense?

**Comment by datapythonista** [comment]
Afaik, the concept of operation in Ibis is (simplifying a bit):
```
SELECT <operations here>
FROM ...
WHERE <operations here>
GROUP BY <operations here>
ORDER BY <operation here>
```
So, things like string functions (e.g. `CONCATENATE`, `SUBSTRING`...), operators (e.g. `+`, `*`...), reductions (e.g. `COUNT`, `SUM`...) are operations. Top-level SQL keywords (e.g. `SELECT, `FROM`...) are not.

I think that's reasonable, and while maybe a way to add these top-level keywords could be nice, that's something that needs to be implemented, since it's not designed in a way that should be extended.

Not sure what you mean by internally. If you mean that this is not going to be part of the BigQuery backend, but a third-party library or your own code, then I'm not sure. I don't know if monkeypatching or subclassing the BigQuery backend is the best way, it's a personal preference I'd say on how to structure your code.

For what Ibis itself is involved, we can propose to add a way to extend these top-level keywords. But if we move forward with using only SQLAlchemy, it is in that project where you should actually propose it (maybe SQLAlchemy is built in a way that it's easier to extend that).

Does this make sense?

**Comment by saschahofmann** [comment]
Yes, I think that's very reasonable 😄 . 

Yes, by internally I mean in the ibis-bigquery backend.

In essence, my question was: can I add functions to a `TableExpr` the same way I can to `StringValue` by using the library ("not internally")? Now the answer seems to be no. And if I understand the above correct then there currently is no easy way to do that.

**Comment by datapythonista** [comment]
If we're understanding each other, I think this function should clarify what I mean: https://github.com/ibis-project/ibis/blob/master/ibis/backends/base/sql/compiler/query_builder.py#L272

Not sure if what you need is "add functions to a TableExpr", or overwriting that method and add a call to a `format_pivot` method you implement.

**Comment by saschahofmann** [comment]
Yes, ok I think that's what I will do.
