### ISSUE TITLE
Raise NotImplementedError if current_database and list_tables do not apply

### ISSUE THREAD

**Issue by datapythonista** [ibis-project/ibis#2962]
Following the discussion on #2912, for backends that doesn't support databases, there are 3 options:

Option 1 (original)
```python
>>> con.current_database
None
>>> con.list_databases()
[]
```

Option 2 (new implemented version, `main` is an arbitrary name)
```python
>>> con.current_database
'main'
>>> con.list_databases()
['main']
```

Option 3
```python
>>> con.current_database
Traceback (most recent call last):
...
NotImplementedError: Backend foo does not support multiple databases
>>> con.list_databases()
Traceback (most recent call last):
...
NotImplementedError: Backend foo does not support multiple databases
```

I think option 1 makes sense in an interactive, but can introduce problems, if for example reusing code from a backend with databases with code reliying on `con.current_database in con.list_databases()`. Or having to handle special cases like `if con.current_database is None:`.

Option 2 solves this problem, but relying on a made up database name may not be ideal.

I would settle on option 3, where code won't fail silently. Maybe we can support it with a boolean attribute `con.supports_databases`, if we think users want to check that, in a nicer way than a try/except.

@cpcloud @jreback how does this sound?

**Comment by cpcloud** [comment]
+1 for option 3.

One issue here is with this phrasing: `Backend foo does not support multiple databases`.

The problem is this doesn't rule out supporting _one_ database, when in fact I believe that most or all the backends that support databases support multiple databases. I could be wrong there, I haven't looked.

Should we phrase it in terms of "support or not support" instead of "may support one or none, but definitely not many"? :)

**Comment by datapythonista** [comment]
Yes, I think removing the word `multiple` improves the message, good point.
