### ISSUE TITLE
TableExpr[i:j] with non-zero i fails if there is no sort_by call

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#311]
See http://www.cloudera.com/content/cloudera/en/documentation/cloudera-impala/v2-0-x/topics/impala_offset.html

Not the best

**Comment by cpcloud** [comment]
The way forward here is to add a property like `supports_limit_without_order_by` to the backend's dialect and fail if it doesn't with an appropriate error messages, since Impala appears to be the only SQL engine we support that actually enforces that limit + offset queries contain an `ORDER BY` clause.

Moving to 0.15.

**Comment by cpcloud** [comment]
Closing as purely an impala problem.
