### ISSUE TITLE
integration: Fugue + Ibis integration

### ISSUE THREAD

**Issue by goodwanghan** [ibis-project/ibis#3211]
Hello Ibis,

I am the creator of the [Fugue Project](https://github.com/fugue-project/fugue). I really like the Ibis project. It's very aligned with Fugue, and both are abstraction layers. I have started experimenting with integrating Ibis into Fugue as another pythonic way to express the compute logic. It is in the latest [pre-release](https://pypi.org/project/fugue/0.6.5.dev2), and here is a [short tutorial](https://fugue-project.github.io/tutorials/tutorials/beginner/ibis.html).

There are a few problems I want to mention:

1. Consistency issues: different backends can have different computing behaviors, see [this](https://fugue-project.github.io/tutorials/tutorials/beginner/ibis.html#consistency-issues)
2. Dask doesn't really work on 2.0.0, but it works on the latest master branch. So can you please release a new version?
3. DuckDB is not an official backend, currently, I am using Postgres backend to compile the SQL to run on DuckDB because it claims to use Postgres syntax.

In general, I really like the programming interface of Ibis and the Fugue integration is very intuitive. Thanks for the great work!

Han

**Comment by cpcloud** [comment]
Hi @goodwanghan 👋🏻! Thanks for your feedback. I'm glad you're finding ibis useful.

Let's just jump right in.

> 1. Consistency issues: different backends can have different computing behaviors, see this

This is a bit of a thorny subject. Forcing all backends to have the same behavior is pretty tricky business, though we do try to ensure this where the effort required to do so is low.

Please open issues for any consistency problems that you encounter and we can take them on a case by case basis. Many of them we are almost certainly willing to tackle.

For the specific case of preserving null grouping keys, it seems like we just need to flip the `dropna` bit to `True` where we use `.groupby` in the pandas-y backends according to [this StackOverflow answer](https://stackoverflow.com/a/61922965/564538).

As for the join case, I suspect we can also make this behavior equivalent, since only the pandas backend needs to be changed (maybe the Dask backend too?)

Both of these are breaking changes, so it'd probably be good to get them into the next (3.0) release.

> 2. Dask doesn't really work on 2.0.0, but it works on the latest master branch. So can you please release a new version?

Please open an issue anyway, if you feel like it, so that we can make sure we don't regress.

That said, there are a few more issues we'd like to close out (the PRs marked with a `breaking change` label and a few other bugs). A 3.0 release is coming up in January. Stay tuned.

> 3. DuckDB is not an official backend, currently, I am using Postgres backend to compile the SQL to run on DuckDB because it claims to use Postgres syntax.

Indeed. In the past, there were folks using Amazon Redshift through the postgres backend in a similar way. Is there benefit to adding a DuckDB backend if its syntax is compatible? If you can't do something with the postgres backend that you'd like to be able to do with duckdb, then it's probably time to consider adding a DuckDB backend.

**Comment by goodwanghan** [comment]
It is indeed challenging to reach consistency between Pandas and SQL. I think Ibis is leaning towards SQL, so I guess it's a good idea to unify all backends' behaviors to SQL behaviors. Fugue is doing the same, it's a lot of effort. See this [test suite example](https://github.com/fugue-project/slide/blob/master/slide_test/suite.py), and it's ongoing. It is possible to create a new Pandas and Dask backend using our implementations to guarantee consistency, but it's still too early to make that decision.

DuckDB is nice because it is very light weighted, and it's embedded. Because a lot of Ibis use cases start from getting tables from a backend, it's valuable to directly support DuckDB, otherwise, we have to [hack](https://github.com/fugue-project/fugue/blob/master/fugue_duckdb/ibis_engine.py). (I am using pandas backend + postgres compiler + duckdb ...)

Looking forward to the release of Ibis 3.0!

**Comment by cpcloud** [comment]
Closing this for now! Let's correspond on the issues we opened. Thanks @goodwanghan.

**Comment by goodwanghan** [comment]
Thank you @cpcloud , I was just about to follow up on this thread. We just released [Fugue 0.6.5](https://github.com/fugue-project/fugue/releases/tag/0.6.5), so although the integration is experimental, it's already in our official release.

I wonder if you have a place to list all collaborating projects? Maybe we should add Fugue project to the list.

**Comment by cpcloud** [comment]
@goodwanghan Awesome! The best place for Fugue is here https://github.com/ibis-project/ibis/blob/master/docs/web/community/ecosystem.md!
