### ISSUE TITLE
Query compiler handles literals incorrectly

### ISSUE THREAD

**Issue by evgenygr** [ibis-project/ibis#4021]
Consider the following code snippet:
```
import ibis

table = ibis.table(name='A', schema=[('a', 'float'), ('b', 'array<int8>')])
expr = table.mutate(b=5)
backend = getattr(ibis, 'duckdb')
str(backend.compile(expr))
```
it produces the following query:
`'SELECT t0.a, CAST(:param_1 AS SMALLINT) AS b \nFROM "A" AS t0'`
whereas the following query is expected, according to [documentation](https://ibis-project.org/docs/3.0.2/ibis-for-sql-programmers/#constant-and-literal-expressions):
`'SELECT t0.a, 5 AS b \nFROM "A" AS t0'`

**Comment by cpcloud** [comment]
Hey Evgeny. Thanks for opening this issue.

We do perform casting of literals in the duckdb backend to give duckdb a hand when inferring the types of bind parameters.

Right now the implementation is heavy handed and casts every literal to it's inferred ibis type. This simplifies the code quite a bit since we don't have to special case anything for different types.

Was this casting problematic for you in some way?

**Comment by cpcloud** [comment]
Hey Evgeny. Thanks for opening this issue.

We do perform casting of literals in the duckdb backend to give duckdb a hand when inferring the types of bind parameters.

Right now the implementation is heavy handed and casts every literal to it's inferred ibis type. This simplifies the code quite a bit since we don't have to special case anything for different types.

Was this casting problematic for you in some way?

**Comment by evgenygr** [comment]
Hey @cpcloud . Thank you for reaching me out.
Today i realized that there is a sensible idea behind this `CAST(:param_1 AS SMALLINT) AS b` way of handling a literal. And decided to close the issue not to distract developers from really actual problems.
Just for educational purposes in case some beginner will read this, let me condense here what i found recently.
Unlike impala engine which compiles directly to a string, duckdb (and mysql, and sqlite, and postgresql) engine compiles to SQLAlchemy's expression which is something more sophisticated, meaning that it takes care of potentially malicious literals that might come from end-user (not from an author of a code which uses ibis). That kind of literals might be an instrument of SQL injection attack. This problem is well-known. For details, one can whatch a [lecture about SQLAlchemy foundations](https://www.sqlalchemy.org/library.html#sqlalchemyanddataaccessinpython). The answers are at the first half an hour of it.
