### ISSUE TITLE
bug(sqlalchemy): unsigned integer produces error at expression compilation

### ISSUE THREAD

**Issue by evgenygr** [ibis-project/ibis#4224]
Unsigned integer types produce error at compilation of expression:
```
import ibis
tbl = ibis.table(name='A', schema=[('a', 'uint64')])
compiled = ibis.duckdb.compile(tbl['a'])
```
Produces `KeyError`, while similar snippet with column `'a'` of `'int64'` type works good.

**Comment by cpcloud** [comment]
@evgenygr Thanks for raising the issue.

There's a refactoring of the internals that convert ibis types to sqlalchemy types that needs to be done to make this work.

The same refactor will allow support for struct field access in the postgres backend as well.

The issue is that we're converting ibis types to sqlalchemy types without considering the dialect of the SQLAlchemy backend, when in fact the various dialects have different levels of support for different ibis types.

You're hitting the case where ibis doesn't know that DuckDB supports unsigned integer types and so can't convert its own types to DuckDB's types.

**Comment by evgenygr** [comment]
Thanks, Phillip! Very instructive details.
