### ISSUE TITLE
docs(api): write a migration guide for the 4.0 release

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#4410]
The `4.x.x` branch contains breaking changes, so we should make a migration guide for both the downstream backend implementors and users. Though the latter may not be required since the user facing API don't change, just the internals.

**Comment by cpcloud** [comment]
[This PR](https://github.com/ibis-project/ibis-bigquery/pull/149) can serve as a reference point for the guide.

**Comment by jcrist** [comment]
With the bigquery backend now moved into the main repo (#4797), were there any high level takeaways that we could turn into a migration guide? If not, do we still want to write up this doc?

**Comment by cpcloud** [comment]
The primary thing to do here is to convert translation rules from this signature:

```python
def rule(translator, expr: ir.Expr):
    ...
```

to 

```python
def rule(translator, op: ops.Node):
    ...
```

Additionally, properties of `op` **no longer require calling `.op()` to access them.

Looking at an example of `expr = t.string_col + "a"`:

**BEFORE 4.0.0**

```
op = expr.op()
left = op.left
right = op.right
left_arg = left.op()
right_arg = right.op() 
```

**AFTER 4.0.0**

```python
op = expr.op()
left_arg = op.left
right_arg = op.right
```

We've made it easier to work with `ops.Node`s since that's much more common than working with `ir.Expr`s.

If for some reason you need to convert an operation back into an `ir.Expr` you can do that with the `Node.to_expr()` method.
