### ISSUE TITLE
Binary operations between pd.Series (ex. obtained via `.filter(...)[...]`)

### ISSUE THREAD

**Issue by ams1** [ibis-project/ibis#4488]
Hi,

I think I came across a bug regarding binary operations at least between 2 x pd.Series.

When running the following code...
```py
import ibis
import pandas as pd
df = pd.DataFrame({'val': [2, 3, 4], 'color':["red","green", "blue"]})
con = ibis.pandas.connect({'df': df})
t = con.table('df')

a = t.filter(t.color == "red")['val'] # this will be 2
b = t.filter(t.color == "green")['val'] # this will be 3
expr = a * b # this should be 6

print(expr.execute())
```
...I get
```
0   NaN
1   NaN
Name: val, dtype: float64
```
...but was expecting
```
0   6
Name: val, dtype: int64
```

---

The problem I think is in:
https://github.com/ibis-project/ibis/blob/dc832d2be538698b3be72789a00fd23cfd3d937f/ibis/backends/pandas/execution/generic.py#L797

**Setting a breakpoint in `_execute_binary_op_impl` revealed that the 2 x pd.Series (left, right) don't have the same index and therefore binary ops fail. (see below debug console screenshot)**

**When doing `reset_index` BEFORE multiplication, I got the expected result.**

**I think the pd.Series (left, right) still have the index from the initial dataframe.**

![image](https://user-images.githubusercontent.com/10154357/189600976-d090bb4d-5155-402b-b492-1fd7a7e494eb.png)

**Comment by ams1** [comment]
Indeed resetting the index BEFORE performing the binary op fixes the bug for pd.Series (sample implementation below).

![image](https://user-images.githubusercontent.com/10154357/189605442-7c58fab2-988f-4491-a3f5-c606104b68ed.png)

NOTE: I think this bug reproduces also case pd.DataFrame (not only pd.Series), therefore maybe a similar mechanism as in `execute_and_reset` should be applied here:

https://github.com/ibis-project/ibis/blob/dc832d2be538698b3be72789a00fd23cfd3d937f/ibis/backends/pandas/core.py#L499-L505

**Comment by cpcloud** [comment]
@ams1 Thanks for the thorough analysis, code and bug report!

I'll have a PR up shortly to fix this.

**Comment by cpcloud** [comment]
@ams1 After running the tests for the other backends, I thought about this some more and realized that this actually the correct behavior.

In SQL land, filtering a table creates a new (logical) table. If you want to add two columns together, each of which comes from a distinct table then you need to join them together.

In this case, pandas' indexing behavior is actually capturing these semantics albeit in a particular way: if you try to add two things with non-overlapping indices (you can think of this as columns coming from two tables that haven't been joined) then pandas does something akin to a full outer join, performing the binary operation where the indexes match and filling nan otherwise.

You can get the behavior you want by doing a join first and then the binary operation.

I understand this probably isn't ideal, but we can't special case this at the expense of the other backends!

Happy to discuss more here, and I'm going to close this out.

**Comment by ams1** [comment]
Good point, I didn't give much thought to the other backends -> so far, for me ibis brings value on top of pandas alone (due to its nicer API AND basic lineage abilities which are IMO essential).

Anyway "driving" through the code so far was a fun ride - i REALLY liked it -> Thank you!
