### ISSUE TITLE
docs(ux): documentation font issue on iOS and MacOS

### ISSUE THREAD

**Issue by CerebralMastication** [ibis-project/ibis#4567]
Hey all, I noticed today that the ibis website renders tables in a really weird way on both iOS and on my macOS using safari in both cases. It looks like this:

![image](https://user-images.githubusercontent.com/126879/192044503-5ab87c3a-7505-4e77-8d4c-47971d4ab1bb.png)

It looks fine in Edge browser in macOS, so seems to be a Safari issue, though I don't know what it is.

**Comment by cpcloud** [comment]
Gosh, that is pretty bad. I wonder if we should just turn off `_repr_html_` for now.

**Comment by cpcloud** [comment]
Thanks for reporting this @CerebralMastication.

It's possible that https://github.com/ibis-project/ibis/pull/4587 fixes the issue, we'll report back here if it does.

**Comment by cpcloud** [comment]
Fixed by #4587.

Verified broken using appetize.io:

![image](https://user-images.githubusercontent.com/417981/194067702-235d8537-a9a8-4b20-aa12-f998f0b73f6b.png)


Verified fixed using appetize.io:

![image](https://user-images.githubusercontent.com/417981/194067782-31986a33-1c16-49f9-a97b-f90efa621264.png)
