### ISSUE TITLE
docs: update README to include clear project value proposition

### ISSUE THREAD

**Issue by MrPowers** [ibis-project/ibis#4665]
I'm having trouble figuring out the value proposition of this project after reading the README & looking at the project website.

Here's the current description:

> Ibis is a Python library to help you write expressive analytics at any scale, small to large. Its goal is to simplify analytical workflows and make you more productive.

Looks like you can create an Ibis table per the [pandas Documentation page](https://ibis-project.org/docs/3.2.0/backends/Pandas/).  But why should I create an Ibis table?  What value does this provide me?

**Comment by MrPowers** [comment]
@cpcloud - what is the main value prop?  That you can use Ibis syntax, write some Pandas code, then switch the backend to PySpark without any code rewrite?

**Comment by cpcloud** [comment]
That depends :)

Are you looking for a one sentence summary, elevator-pitch-like blurb? Or a bulleted list of reasons why, or something longer form like a paragraph?

**Comment by MrPowers** [comment]
@cpcloud - elevator pitch / something longer would be ideal ;)

I'm going to try and write a blog post on using Ibis to query a Delta Lake table.  A little bit more high context info will hopefully help me understand the value Ibis adds for data engineers in this context.

**Comment by saulpw** [comment]
@marlenezw We probably could use a better tagline/one-liner/elevator pitch for Ibis, do you have any ideas for what that process might look like?

**Comment by wjones127** [comment]
My quick take (though the Ibis devs might have better ideas), is there are two purposes to Ibis:

 1. To avoid writing queries as strings (“stringly-typed analytics” as Phillip has derogatorily called it)
 2. To allow easy switching between various backends (“write once, run anywhere” as Java used to say)

A particular use-case that takes advantage of both of these is being able to write functions that encapsulate common domain-specific transformations. In my past job, I wrote a library of various functions that works on PySpark expressions that I reused across my Spark jobs. Having that kind of abstraction avoids a lot of copy-and-pasted SQL (purpose 1). But it would have been even cooler if I had written them in Ibis, since I could then have tested them against small Pandas datasets and also been able to reuse them for my Snowflake queries (purpose 2).

**Comment by saulpw** [comment]
Thanks @wjones127 !  Good thoughts.

Here's a pitch that's very focused on SQL, which isn't the complete story (Ibis can query non-SQL backends too), but might be useful for people like @MrPowers who are coming to Ibis without knowing what it does at all:

> SQL is difficult to parameterize, to compose expressions, to check for type errors before executing, and to extend its syntax for your own needs.  The Python languages makes all of these things much easier, but the main ways to access databases still require generating text SQL queries.  Ibis does this work for you, so you can create Python expressions to execute against databases without having to write SQL.  

To your second purpose, you can't quite "write once, run anywhere", as backends have widely varying support for data types and features, but you *can* "learn once, write anywhere", as the same Ibis syntax and language is used, regardless of database support.  (And Ibis can usually tell you before execution if the backend doesn't support a feature you're using.)

**Comment by marlenezw** [comment]
@MrPowers If you decide to write out a blogpost let me know! I'd be happy to help you edit or promote it once it's ready! Also @saulpw I'll chat to Patrick about this and see if we can help with the elevator pitch too! It could be good to combine perspectives to make sure we don't miss anything out :D
