### ISSUE TITLE
ci: run semantic-release step is failing in CI

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#4697]
This is currently failing in all PRs. See e.g. https://github.com/ibis-project/ibis/actions/runs/3297592264/jobs/5438594126.

**Comment by cpcloud** [comment]
These problems are usually caused by release artifacts for the same version being uploaded at different points in time.

They can be "fixed" by clearing your local cache and running `poetry lock --no-update`.

It's on my list to figure out how to address this while retaining the ability to verify the lock file.
