### ISSUE TITLE
feat(ux): expose `_find_backend` as a public method on TableExpr

### ISSUE THREAD

**Issue by gforsyth** [ibis-project/ibis#5064]
### Is your feature request related to a problem?

Before `ibis.read` existed, there wasn't a way to get a table expression without either making a connection to a backend, or creating an unbound table.

Now though, it's possible to get a TableExpr from `read` without knowing which backend you are running on.  For now, this is almost always `duckdb`, but that may change.

### Describe the solution you'd like

I think we could provide a public version of `_find_backend` -- more akin to the `name` attribute on connections, so that new users can check what backend their table expression is running against.

### What version of ibis are you running?

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
I'd expect this to be a relatively rare operation - perhaps a new top-level function would be better than a method on all expressions (to avoid cluttering the expression namespace). What about something like:

```python
def get_backend(expr: ir.Expr | None = None) -> BaseBackend:
    """Get the backend for an expression, or the default backend if no expr passed or no backend bound on the expr"""
    ...
```

**Comment by gforsyth** [comment]
that makes sense to me

**Comment by NickCrews** [comment]
My usecase for this:

I have an external data file `names.csv` which contains a list of ~150k valid names. I have a function `def is_name(input: StringColumn) -> BooleanColumn` that checks if the input is contained in that csv. To do that efficiently I need to load the csv file into the database, so I can then do a check using a JOIN, since `input.isin(<python list>)` is very slow. To load it in the database, I do

```python
be = input._find_backend()
names = be.read_csv(NAMES_PATH)
...joining...
```

**Comment by jcrist** [comment]
Added in #5260.
