### ISSUE TITLE
bug: order_by() with non-existent column does not error

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#5214]
### What happened?

I would expect order_by(DNE) to fail. But instead it silently gives me back the original unsorted table:

```python
import ibis
import pandas as pd

df = pd.DataFrame({"x": [3,1,2]})
t = ibis.memtable(df)
t.order_by("bogus")
┏━━━━━━━┓
┃ x     ┃
┡━━━━━━━┩
│ int64 │
├───────┤
│     3 │
│     1 │
│     2 │
└───────┘
```

### What version of ibis are you using?

4.0.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report and the minimal reproducible example! We should be able to fix this for 4.1, slated for a week or two from now.

**Comment by cpcloud** [comment]
Looking into this, there's a simple but likely not obvious explanation for what's happening:

The ibis input rule for the `sort_keys` field of `Selection` operations is basically: "try to find a column in the child table, otherwise treat the value as an expression"

The latter part of that validation

> otherwise treat the value as an expression

causes the sort key to be the constant string `'bogus'`.

This is equivalent to writing:

```sql
SELECT x
FROM t
ORDER BY 'bogus'
```

Indeed that is what is output by `ibis.show_sql`:

```
In [6]: ibis.show_sql(t.order_by("bogus"))
SELECT
  t0.x
FROM _ibis_memtable0 AS t0
ORDER BY
  CAST('bogus' AS TEXT)
```

Since ordering by a constant value is equivalent to no `ORDER BY` there's no effect on the input relation.

I think this is probably confusing and unexpected behavior even though it is correct.

I see a at least two options:

1. Disallow strings as arguments to `order_by`. I think this is inconsistent with the rest of the places where we convert strings to columns so it's probably not a good idea.
2. Allow strings as arguments, but require any literal strings to be wrapped in `ibis.literal`. This is currently how `t.select` works, and we would make `order_by` consistent with that.

One wrinkle here is that in ibis we allow the SQL ordinal shorthand syntax for `order_by`, which allows you to refer to columns in `ORDER BY` using one-based ordinal offsets. I think we can handle this by making the `ops.SortKey.arg` rule more specific than `rlz.any` 😅.

I personally am in favor of option 2.

Thanks for this report @NickCrews, it's a nice edge case find.

**Comment by jcrist** [comment]
Yeah, option 2 makes sense to me. For `order_by(some_int)` case are you saying you'd also make that error for an integer literal that indexed > the number of columns?

**Comment by NickCrews** [comment]
Yes option 2 sounds great! I think a note on `ibis.literal` would be good to include in the docstring when that fix goes in.
