### ISSUE TITLE
docs: describe schema declaration using type annotations

### ISSUE THREAD

**Issue by kszucs** [ibis-project/ibis#5410]
Follow up for https://github.com/ibis-project/ibis/pull/5330

**Comment by NickCrews** [comment]
Would this allow me do:

```python
class PeopleTable:
    name: str
    age: int

def is_adult(t: PeopleTable):
    return t.age > 18
```
and I get tab autocompletion etc because tooling knows that t has an attribute "age" and it is an int? Ideally mypy could even catch this in the future. I would LOVE both/either of these features.

**Comment by kszucs** [comment]
That doesn't work in that form, but the following already works:

```py
@ibis.table
class PeopleTable:
    name: str
    age: int

def is_adult():
    return PeopleTable.age > 18
```

In the example `PeopleTable` would be an ibis table instance which may not be desired (cc @jcrist). On the other hand we could introduce a metaclass to implement your example. What is the advantage of using a PeopleTable instance instead of the class?

**Comment by NickCrews** [comment]
> ```python
> @ibis.table
> class PeopleTable:
>     name: str
>     age: int
> 
> def is_adult():
>     return PeopleTable.age > 18
> ```

What would this even do? I don't think anything useful?

> What is the advantage of using a PeopleTable instance instead of the class?

Sorry, my example wasn't exactly right, when I am actually doing my processing, I am passing around instances of ibis.expr.types.Table, but I want to notate that they follow the schema of PeopleTable. This is more what I mean:

```python
from ibis.expr.types import Table

class PeopleTable:
    name: str
    age: int

def is_adult(t: Table[PeopleTable]):
    # tab completion, syntax highlighting, (ideally) mypy work
    # because we know that `t` has an column `age` of type string
    return t.age > 18.
```

This is inspired by how you can annotate tables to be of a certain schema with [pandera](https://pandera.readthedocs.io/en/stable/schema_models.html#basic-usage) (except in pandera you can do a lot more like runtime checks, coercing, etc. I'm not looking for that. Just the type hints)

**Comment by jcrist** [comment]
Python type annotations currently can't convey or reason about dataframe operations like this. There's no way to tell `mypy`/`pyright` what the output of schema-changing operation would be (`select`, `mutate`, `agg`). To be fair to python, these are hard operations for _any_ language to annotate.

`pandera` hacks around this by requiring users annotate their functions with schemas, and providing a `mypy` plugin to parse these custom annotation types. I'd be against taking that route in Ibis because:

- It would only work with `mypy`. `pyright` doesn't support extensions like this, neither does `pycharm` or other static analysis tools. Since `pyright` is commonly used with vscode, this would cut off support for a large section of users.
- `mypy` plugins are quite hard to maintain. The internals of `mypy` change, and developing your own plugin is not well documented.
- Dataframe operations are hard to type infer, requiring the users manually annotate their functions to express schema transformations.
- Most ibis users are working interactively, where our tab-completion _can_ support these use cases. Putting limited developer resources into improving annotations in a static environment doesn't feel worth it to me.

While I can sympathize with your desires here, I don't see a feasible way to make this work given the current state of python type annotations.

**Comment by NickCrews** [comment]
Ah, I didn't know that, but that makes sense. Darn.

OK, I can give up mypy/pyright deducing types in general, but can we still support manual annotations for syntax highlighting and tab completion? eg `new_df: Table[NewSchema] = old.mutate(...)` 80% of the time I am not in an interactive environment and the existing tab completion doesn't work (when it does, I LOVE it, thank you!). IDK how many resources that would take, I understand that it is non-zero. I can split this into a separate issue and we can see how many others upvote it if you want.

**Comment by lostmygithubaccount** [comment]
closing in favor of #6844
