### ISSUE TITLE
feat(io): add option to write a table expression as a partitioned parquet folder

### ISSUE THREAD

**Issue by ogrisel** [ibis-project/ibis#5532]
### Is your feature request related to a problem?

At the moment (since #4444) there is a generic implementation of the `to_parquet` method in `ibis/ibis/backends/base/__init__.py`'s `_FileIOHandler` that uses pyarrow's `ParquetWriter`:

```python
        import pyarrow.parquet as pq

        batch_reader = expr.to_pyarrow_batches(params=params)

        with pq.ParquetWriter(path, batch_reader.schema) as writer:
            for batch in batch_reader:
                writer.write_batch(batch)
```

This works for all backends that to support `to_pyarrow_batches` which is nice. However, this abstraction makes it impossible to leverage backend-specific features such as partitioned writing. For instance, since duckdb 0.7.0 it is possible to use:

```sql
COPY orders TO 'orders' (FORMAT PARQUET, PARTITION_BY (year, month));
```

See the [duckdb 0.7.0 announcement](https://duckdb.org/2023/02/13/announcing-duckdb-070.html#data-ingestionexport-improvements) for more details.

which is very nice to generate parquet files trees that can be very efficiently queried upon by any DB engine that supports predicate push downs down to the parquet folder structure, especially when those files are meant to be archived in a large cloud object store ("data lake").

### Describe the solution you'd like

Either find a way to generate partitioned parquet writes while still relying on `to_pyarrow_batches` of the generic `_FileIOHandler` but I am not sure how this would be possible with the `ParquetWriter` API.

Alternatively, find a way to use [pq.write_to_dataset](https://arrow.apache.org/docs/python/parquet.html#writing-to-partitioned-datasets) but I am not sure if this is possible to use this API incrementally with a generator that yields arrow tables, chunk by chunk.

Finally, one could specialize the `to_parquet` method for datasets that already support writing to partitioned parquet datasets such as DuckDB. But then I am not sure about the impact of non-default data set handling, e.g. writing to an `s3://` folder. The potentital discrepancies between pyarrow filesystem support and duckdb's might cause new UX problems.

### What version of ibis are you running?

ibis master

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for opening this @ogrisel.

I agree that the option to write out to partitioned parquet folders is both useful and desirable.

And I think that you've hit on the available approaches, and their downsides.

I've looked at the `ParquetWriter` and `pq.write_to_dataset` APIs:

`ParquetWriter` supports `RecordBatchReader`s but does not write to partitioned folders.

It is possible to create a `pyarrow.dataset` from a `RecordBatchReader` but this materializes the entire dataset in-memory, which would limit the possible dataset size that Ibis can handle (which we don't want to sacrifice).

I'm inclined to define special `to_parquet` methods per-backend, because there are going to be specialized methods (and certainly, for something like Snowflake or BigQuery, it's certainly preferable if the output location is an S3 bucket that we don't first pull the recordbatches back to a laptop and _then_ ship them off to S3).

But there are going to be problems here, too.
One of the reasons we started using Arrow in the first place (for parquet reading) was because DuckDB has a hand-rolled implementation of the AWS auth stuff which doesn't allow for numerous methods of authenticating to an S3 bucket.  Last I checked, they don't support the standard AWS environment variables, nor do they handle instance auth.

I'm not sure how to handle this.  As it stands right now, we won't be able to offer every combination of functionality.

**Comment by gforsyth** [comment]
The other (probably horrible) option I can think of is to write our own handling for `RecordBatchReader` -> Partitioned parquet folder.  I think this would be... gross.  And since I think we would have to write out each row-group individually, there would probably be individual parquet folders in a given partition location that would end up with only a handful of rows.

I'll think about this some more, and ask some questions to the people who know Arrow a lot better than I do and see if anyone has any thoughts on how to proceed.

**Comment by gforsyth** [comment]
Ok, I checked with a colleague and it looks like `pyarrow.dataset.write_dataset` supports writing `RecordBatchReader` to partitioned parquet files without materializing the entire thing in memory (:tada:).

The difference between that and current behavior is that we'll probably default to writing out parquet file(s) to a directory, even if it's just a single file, but we can support writing in directory partitioning, hive partitioning, and filename partitioning

**Comment by jcrist** [comment]
> The difference between that and current behavior is that we'll probably default to writing out parquet file(s) to a directory, even if it's just a single file

I think is fine. If/when we dispatch writing to be handled by backends themselves (rather than going through pyarrow), I think a directory of files will be easier to support anyway than a single file. Most large scale systems don't (easily) support outputting a single file.

**Comment by cpcloud** [comment]
It does somewhat downgrade the local experience since most of our local-only engines don't directly support a directory of parquet files. Perhaps that's something ibis can provide by just slapping a glob on the end of a directory path for the backends that don't support it.

**Comment by gforsyth** [comment]
Ok, because of the _many_ differences between backends and their support (or lack thereof) for both reading AND writing partitioned parquet files, this is much less trivial to do than initially expected.

For the time-being, we are passing through keyword arguments to the `duckdb` parquet writer (and not using `pyarrow`) so for the `duckdb` backend you can get `hive` partitioning by using the `partition_by('col1', 'col2')` keyword argument in the `to_parquet` call.

DuckDB will also read this in correctly, although DuckDB currently requires you to manually specify the level of globbing for a nested parquet directory structure, e.g. for

```
duckdb.parquet/
---year=1992/
  --- data_0.parquet
---year=1993/
  --- data_0.parquet
```

you would do `con.read_parquet("duckdb.parquet/*/*", table_name=...)`

There's an upstream issue to track adding recursive globbing.

**Comment by NickCrews** [comment]
In case anyone needs it, this is the bit of util code that I have, hopefully you can adopt it to your needs:

<details>
  <summary>Code</summary>
  
```python
from __future__ import annotations

import logging
from pathlib import Path
import shutil

from ibis.backends.duckdb import Backend as DuckDBBackend
from ibis.expr.types import Table

logger = logging.getLogger(__name__)


def to_many(
    t: Table,
    output_dir: Path,
    pattern: str = "chunk-{i:03}.parquet",
    chunk_size: int = 1_000_000,
) -> None:
    """Write an ibis table to many parquet files in the given directory.
    
    Depending on the input, you may want to persist the table before
    calling this function, because otherwise it could get evaluated
    over and over again for each chunk."""
    output_dir = Path(output_dir)
    ensure_empty_dir(output_dir)
    out_pattern = str(output_dir / pattern)
    logger.info(f"Exporting to {out_pattern}")
    _write_ibis_parquet_chunks(t, out_pattern, chunk_size)


def ensure_empty_dir(path: Path, force: bool = True) -> None:
    """Force a directory to be empty"""
    path = Path(path)
    if path.exists():
        if not path.is_dir() and path.glob("*") and not force:
            raise ValueError(f"Path {path} is not an empty directory")
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()
    path.mkdir(exist_ok=True, parents=True)


def _write_ibis_parquet_chunks(
    table: Table, out_pattern: str, chunk_size: int = 1_000_000
):
    nrows = table.count().execute()
    for i, offset in enumerate(range(0, nrows, chunk_size)):
        chunk = table.limit(chunk_size, offset=offset)
        path = out_pattern.format(i=i)
        _write_ibis_parquet(chunk, path)


def _write_ibis_parquet(table: Table, path: str | Path):
    backend = table._find_backend()
    if not isinstance(backend, DuckDBBackend):
        raise ValueError(f"Unsupported backend {backend}")
    path = _fix_path(path)
    name = "adskfjasdfaksdhjfgkasdhjfgkasdjhfkad" # lololololol this isn't great
    table.alias(name)
    sql = f"COPY {name} TO '{path}' (FORMAT 'parquet')"
    backend.raw_sql(sql)


def _fix_path(path):
    """Convert a path either to an absolute path and create parents"""
    path = Path(path)
    path = path.absolute()
    path.parent.mkdir(parents=True, exist_ok=True)
    return path

  ```
</details>

**Comment by ogrisel** [comment]
> For the time-being, we are passing through keyword arguments to the duckdb parquet writer (and not using pyarrow) so for the duckdb backend you can get hive partitioning by using the partition_by('col1', 'col2') keyword argument in the to_parquet call.

I think this is good. I assume you are referring to #5636 or do you have other PRs in mind?

I think it would be good to have tests to progressively check that it's possible to read/write to/from partitioned parquet folders for the backends that support it.

Also the docstring should be more explicit on how to achieve this, possibly with an example code snippet somewhere (maybe at the end of the docstring).

> There's an upstream issue to track adding recursive globbing.

Link?

**Comment by gforsyth** [comment]
> I think this is good. I assume you are referring to #5636 or do you have other PRs in mind?

Yes, I was referring to that PR.



> I think it would be good to have tests to progressively check that it's possible to read/write to/from partitioned parquet folders for the backends that support it.

I agree -- for now, that will just be DuckDB but I'll add it to all backends with some `xfails` so we can track it.

> Also the docstring should be more explicit on how to achieve this, possibly with an example code snippet somewhere (maybe at the end of the docstring).

I will add an example.



> > There's an upstream issue to track adding recursive globbing.
> 
> Link?

Issue: https://github.com/duckdb/duckdb/issues/5897
Recent PR: https://github.com/duckdb/duckdb/pull/6627

**Comment by ogrisel** [comment]
Thanks. Shall we close this issue or shall we keep it open to find a generic, PyArrow-based solution for backends that cannot natively write to partitioned parquet folders?

**Comment by gforsyth** [comment]
I think we can close this out -- there will be a larger push to try to standardize reading and writing partitioned parquet files at some point in the not-too-distant future.
