### ISSUE TITLE
refactor(type-system): give love to decimal type inference

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#557]

**Comment by cpcloud** [comment]
@jacques-n Are there any specific test cases we should be exercising to ensure decimal correctness?

**Comment by jacques-n** [comment]
I'd definitely crib [the tests](https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/test/java/com/dremio/BaseDecimalFunctionTests.java#L40) from Dremio that are easy to repurpose.

The scale/precision output compromises are always the key pain points when working with Decimal. Having good coverage of the edge cases related to these are important.

For note, the pattern used in the tests linked above are an expression using a [simple expression language](https://github.com/dremio/dremio-oss/tree/50a4497189d426fdf5b1b2a515d9ac1012c5be1c/sabot/logical/src/main/antlr3/com/dremio/common/expression/parser) where the pattern argument pattern is expression followed by one or more column values (referenced in the expression as c0, c1, ... cN). In Dremio, this pattern is used to make sure you don't get fast-pathed for literals. 

FYI, in many systems, literal handling has different type derivation behaviors because the interpreter can make decisions based on the actual precision/scale of the data (as opposed to having to make decisions on the output type without knowing the actual data). I recall SQL Server being especially notorious in this way.  Be cognizant of this when validating results against different databases.

**Comment by cpcloud** [comment]
Fixed #4334
