### ISSUE TITLE
bug:  mixing deferred underscore api with top level expression fails

### ISSUE THREAD

**Issue by thegreymatter** [ibis-project/ibis#5597]
### What happened?

I'm having an unexpected behavior when trying to mix the deferred underscore api with top level expression

While this snippet doesn't work.

    df = pd.DataFrame({'id': [1, 2, 1, 1, 5], 'type': ['A', 'A', 'B', 'B', 'C']})
    table = ibis.memtable(df).mutate(value=1)

    pv = table.group_by(_.id)\
        .aggregate({"c1": ibis.case().when(_.type == "A", _.value).end().sum(),
                    "c2": ibis.case().when(_.type == "B", _.value).end().sum()})
    print(pv.execute())

with the following error 
`ibis.common.exceptions.IbisTypeError: The datatype of value <ibis.expr.deferred.Deferred object at 0x11e9743d0> cannot be inferred, try passing it explicitly with the type keyword.`

This snippet does work.

    df = pd.DataFrame({'id': [1, 2, 1, 1, 5], 'type': ['A', 'A', 'B', 'B', 'C']})
    table = ibis.memtable(df).mutate(value=1)

    pv = table.group_by(_.id)\
        .aggregate({"c1": ibis.case().when(table.type == "A", table.value).end().sum(),
                    "c2": ibis.case().when(table.type == "B", table.value).end().sum()})
    print(pv.execute())

my guess up until now is that top level expression treat deferred as literals.
any thoughts if it's by design or not? 

### What version of ibis are you using?

4.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@thegreymatter Yeah, this is tricky :) We have an issue to track its implementation (#4382) but as of now no one has tried implementing it.

The primary problem is that our operation classes all require non-deferred inputs. `ops.SearchedCase` is the operation you're using here.

When an expression is built off of `_`/`deferred`, the receiver of the deferred (only a table receiver is supported right now) can pass itself to `_.resolve` to "undefer" the expression.

When a deferred object occurs somewhere in the middle of some other expression we can't construct that expression, because we're below the calling table's resolution step (this happens in `select`, `agg` and `filter`).

I'm not sure what a solution would look like here.

One approach might be to somehow turn any expression that contains a deferred object into its deferred version, and simply continue to disallow operations to accept deferreds.

The downside of this is that it will probably be a game of whack-a-mole, going through the top-level APIs one by one and adding tests to verify that using deferreds works.

**Comment by cpcloud** [comment]
Closing this in favor of #4382. This would be an interesting exploration for someone to do.

It's not immediately obvious whether this is possible in a reasonable way.
