### ISSUE TITLE
Add extension rules for TINYINT types in SQLAlchemy

### ISSUE THREAD

**Issue by wesm** [ibis-project/ibis#589]
sqlalchemy doesn't come with built-in support for TINYINT; for supported databases this would be nice to have

**Comment by cpcloud** [comment]
This already exists in core sqlalchemy for database that that library supports, otherwise upstream drivers need to implement their own types.

The one piece of work that would likely need to be done in ibis is verifying that we correctly map those upstream driver types to an ibis type. This is done already for mysql. The others can be done as needed.
