### ISSUE TITLE
bug: Impala Documentation is out of date

### ISSUE THREAD

**Issue by matthias-Q** [ibis-project/ibis#5976]
### What happened?

I was following https://ibis-project.org/backends/Impala/ and most of the things described there are not working anymore. The docstrings seem to be out of date.
For example in the first connection example:
```
>>> hdfs = ibis.impala.hdfs_connect(host=hdfs_host, port=hdfs_port)
```
returns an error: `AttributeError: module 'ibis' has no attribute 'impala'`

### What version of ibis are you using?

5.1.0

### What backend(s) are you using, if any?

Impala

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Thanks for letting us know, @matthias-Q !  

We recently restricted the available methods in the `ibis.<backend>` namespace to avoid running commands on unconnected backends.

For a quick workaround, you can run `ibis.backends.impala.hdfs_connect` instead.

@jcrist -- do we have a policy on how many (if any) special cased methods we want to make available in the ibis backend proxy objects?
I would err on the side of allowing `ibis.impala.hdfs_connect` because it gets passed to a subsequent `ibis.impala.connect` call.
