### ISSUE TITLE
join documentation not up to date

### ISSUE THREAD

**Issue by wleescor** [ibis-project/ibis#6215]
I am using the latest version of ibis (5.1.0) 
the join function (and left_join) doesn't seem to be documented properly. In the documentation (https://ibis-project.org/api/expressions/tables/?h=join#ibis.expr.types.relations.Table.join) expecting lname and rname arguments. but version 5.1.0 is showing me expecting suffixes argument. I'm not sure whether the documentation or the code is correct.

```python
data = ibis.memtable({"A": [1, 2, 1, 1, 2, 2],
        "B": ["a", "b", "a", "a", "b", "c"]})
lookup = ibis.memtable({"A": [1, 2, 3, 4, 5, 6],
        "C": ["aa", "bbb", "acc", "addd", "bee", "cff"]})

data.join(lookup, 'A', how='left') gives me 
┏━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┓
┃ A_x   ┃ B      ┃ A_y   ┃ C      ┃
┡━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━┩
│ int64 │ string │ int64 │ string │
├───────┼────────┼───────┼────────┤
│     1 │ a      │     1 │ aa     │
│     2 │ b      │     2 │ bbb    │
│     1 │ a      │     1 │ aa     │
│     1 │ a      │     1 │ aa     │
│     2 │ b      │     2 │ bbb    │
│     2 │ c      │     2 │ bbb    │
└───────┴────────┴───────┴────────┘
```

with default suffixes _x and _y. The documentation says that I would expect _left and _right with default behaviour no suffix.

Firstly, the documentation should be updated to match the package.
Secondly, ideally I think it should be better that the default would be no suffix (if there were no duplicates) like pandas and most other backends. 
Thanks

**Comment by jcrist** [comment]
> Firstly, the documentation should be updated to match the package.

It's rather the package that should be updated to match the docs :) (we need to cut a new release).

Currently the documentation tracks the `master` branch. Usually this isn't a problem (features are strictly additive, so users are unlikely to run into issues with docs mismatches). In this case though the documentation is about an upcoming breaking change. The behavior you see on `ibis-project.org` is the _upcoming_ join behavior, the previous join behavior is the behavior you're seeing with `_x` and `_y` suffixes.

We could update our docs process to not publish docs until the release, but since this is the first user issue to run into this, I'm tempted to hold off changing our process until a few others run into issues. There's some benefit to being able to update the docs between releases, I'd hope to avoid losing that benefit.

> Secondly, ideally I think it should be better that the default would be no suffix (if there were no duplicates) like pandas and most other backends.

We can only avoid adding column suffixes for inner joins for columns joined with an equality predicate. All other join configurations have to have to deduplicate, since either the left or right version may differ. The new behavior was deemed the most ergonomic solution - by default collisions in the `right` table are renamed, which plays better when chaining multiple joins together.

**Comment by gforsyth** [comment]
Thanks for opening this, @wleescor -- I'm going to close the issue out as I think Jim has explained what's going on.
