### ISSUE TITLE
feat: more forgiving dtype comparisons

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#6738]
### Is your feature request related to a problem?

I want an easy way to check if a column is a certain dtype:

```python
import ibis
ibis.examples.penguins.fetch().species.type() == "string"  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == "STRING"  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == str  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == "str"  # gives False, probably should stay false  EDIT: actually this should be True
ibis.examples.penguins.fetch().flipper_length_mm.type() == "int64"  # gives False, I want true
ibis.examples.penguins.fetch().flipper_length_mm.type() == "INT64"  # gives False, I want true
# gives False, I'm not sure what should happen here...
# uint dtypes should definitely not be == to `int` though
ibis.examples.penguins.fetch().flipper_length_mm.type() == int
```

### Describe the solution you'd like

I think casting other to a an ibis dtype for the comparison would lead to things always being consistent?

```python
def __eq__(self, other) -> bool:
   casted = ibis.cast_to_ibis_dtype(other)  # noop if already a dtype
   return self == casted
```

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Have you seen the `is_...` methods on the types?

```python
>>> t.species.type().is_string()
True
>>> t.bill_length_mm.is_integer()
False
>>> t.bill_length_mm.is_floating()
True
```

**Comment by NickCrews** [comment]
They are sufficient, but not the best experience. When I don't have tab completion available these aren't obvious. I was actually looking to test if it was a uinteger, so I blindly tried both `.is_uint()` and `.is_uinteger()` and neither worked. I eventually ended up with `x.type() == ibis.literal(4, type="uint64").type()`, which is disgusting, because that was easier than me looking up the docs. In fact, that wouldn't have even helped, because these methods aren't in the docs.

**Comment by jcrist** [comment]
> That's easy to fix, I can push up a PR.

See https://github.com/ibis-project/ibis/pull/6739

**Comment by NickCrews** [comment]
> any editor auto-completion working from type analysis should show them as available

I didn't have that available either. Adding them to the docs is good, but I still think `type() == <>` is very intuitive and should be supported. This is just me, but I know that in the future my first inclination is going to be to reach for this paradigm than the .is_<>() method. Pandas supports this: `ibis.examples.penguins.fetch().to_pandas().year.dtype == "int64"`. I think hearing from some other ibis users would be useful here. Should I start a survey in a discussion?

If the required code is just the overridden __eq__ method as I have above, would you be willing to support it? If the required code is more complex then I can shut up :)

**Comment by jcrist** [comment]
Yeah, I don't disagree that this could be a sane feature to add, I was just trying to point out methods that exist today.

`numpy`, `pyarrow`, and `pandas` all support some amount of coercion in dtype comparisons, supporting this in ibis seems reasonable. Note that numpy's implementation of this has resulted in real bugs in the past due to this fun behavior:

```python
In [1]: import numpy as np

In [2]: np.dtype("f8") == None  # wat
Out[2]: True

In [3]: np.dtype(None)  # this is due to None (the default) being coerced to f8
Out[3]: dtype('float64')
```

Due to our class hierarchy my initial attempts to define `__eq__` manually this way led to some weird issues, and it wasn't clear (to me) which of our own magic methods should be overridden to implement this (`__equals__`? `__cached_equals__`?). cc @kszucs for advice on how these classes are supposed to be extended here.

**Comment by cpcloud** [comment]
@NickCrews I hear what you're saying: it can be very inconvenient for a library to be a bit more strict about comparisons.

I am -1 on magic comparisons due to the potential for misuse and confusion, and also having to support many different flavors of input.

It also complicates the codebase to have additional places where we have to normalize string inputs (we have a good number of these already).

**Comment by cpcloud** [comment]
The string example is a good example of where things could go haywire:

``
ibis.examples.penguins.fetch().species.type() == "string"  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == "STRING"  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == str  # gives False, I want true
ibis.examples.penguins.fetch().species.type() == "str"
```

Why would `"str"` be invalid? It's already allowed as input to `ibis.schema`.

**Comment by jcrist** [comment]
> I am -1 on magic comparisons due to the potential for misuse and confusion, and also having to support many different flavors of input.

I'd agree that there are places where we probably want to only accept true `DataType` instances rather than strings, but doing some coercion in `__eq__` feels fine to me (and I once lost a few hours to the numpy issue noted above).

Pyarrow implements this by trying to coerce `other` to a type, and returning `NotImplemented` if it's not a valid type (see [here](https://github.com/apache/arrow/blob/f44e28fa03a64ae5b3d9352d21aee2cc84f9af6c/python/pyarrow/types.pxi#L280-L314)). In ibis this would naturally be something like:

```python
def __eq__(self, other):
    if not isinstance(other, dt.DataType):
        try:
            other = dt.dtype(other)
        except TypeError, ValueError:
            return NotImplemented
    return self.equals(other)
```

This definitely adds the ability for typos to creep in (`dtype == "string"` would return True for string dtypes and false otherwise, `dtype == "strng"` would always return false). But going with our existing dtype parsing/coercion rules rather than what @NickCrews posted above, the semantics seem well defined and easy enough to implement.

**Comment by jcrist** [comment]
As a compromise, I've pushed up a PR adding `ibis.dtype` as a top-level API (#6741). I still think coercion as part of `__eq__` might make sense, but if that ends up not being something we do you can always simulate it yourself by using `ibis.dtype` directly:

```python
table.some_col.type() == ibis.dtype("int32")
```

**Comment by NickCrews** [comment]
> ibis.dtype as a top-level API

This looks great, and I'd be happy with just this. The coercion in `__eq__` would be great but I would be fine closing this as a longer term nice-to-have

**Comment by NickCrews** [comment]
> Why would "str" be invalid?

I change my mind, per what you say then `.type() == "str"` should be True.

**Comment by NickCrews** [comment]
> dtype == "strng"

is there a problem with raising a ValueError here? eg don't catch the ValueError here:

```python
def __eq__(self, other):
    if not isinstance(other, dt.DataType):
        try:
            other = dt.dtype(other)
        # except TypeError:
        except (TypeError, ValueError):
            return NotImplemented
    return self.equals(other)
```
I expect I'm missing something here.

**Comment by kszucs** [comment]
I'd also prefer not to do implicit string to datatype coercion on equality checks, `expr.type() == ibis.dtype(typestring)` should provide enough flexibility.

**Comment by jcrist** [comment]
Since exposing `ibis.dtype` has been merged and coercion in `__eq__` has some opposition, I'm going to close this issue (kind of) resolved. As always, thanks for the useful feature discussion @NickCrews!
