### ISSUE TITLE
docs: Explain what "releasing a cursor" means for `raw_sql` 

### ISSUE THREAD

**Issue by fleimgruber** [ibis-project/ibis#6841]
### Is your feature request related to a problem?

I am reading the docs and later the code to find this explanation: https://github.com/ibis-project/ibis/blob/87a099c5dd83bd95c44c9c7bfbb9a0d2f4e2837d/ibis/backends/base/sql/__init__.py#L132

### Describe the solution you'd like

I would expect to see hints on what releasing a cursor means and how to accomplish it, e.g. how to convert the query results to a Pandas DataFrame.

### What version of ibis are you running?

6.1.0

### What backend(s) are you using, if any?

PostgreSQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@fleimgruber 👋🏻 Hi! Thanks for opening the issue!

> I would expect to see hints on what releasing a cursor means and how to accomplish it

Fair enough!

> how to convert the query results to a Pandas DataFrame.

Enumerating all the ways this can be done from the result of `raw_sql` isn't really in scope for us. After all, one of the things ibis does for you is worry about the details of converting query results to various in-memory formats including pandas DataFrames.

Have you tried using `con.sql` instead of `raw_sql`, or `table.sql` (for running SQL against arbitrary ibis expressions)?

`raw_sql` should be used as a last resort or for things that don't return results like DDL.

`con.sql` and `table.sql` will handle the in-memory-results conversion for you, perhaps obviating your need to use `raw_sql`.

**Comment by fleimgruber** [comment]
Thanks for the fast reply, explanation and documentation! My bad for not having browsed the docs a bit longer to find the `con.sql` and `.execute()` which are exactly what I needed.
