### ISSUE TITLE
Create lowest common denominator set of benchmarks for different backends

### ISSUE THREAD

**Issue by kszlim** [ibis-project/ibis#7032]
Would be very useful/informative to have a benchmark that runs the same frontend query on all the backends (or most of them). Would also help to track any performance regressions from potentially how the queries are being translated into their backend constituents.

**Comment by gforsyth** [comment]
Hey @kszlim -- thanks for raising this!

Are you interested in this to provide a general baseline for how the various execution engines / backends compare to one another with regards to their performance?

It would be nice to have a simple place to compare these things, but it's also something that is impossible to do well.  Benchmarks are inherently biased, where some classes of problems will perform better on certain engines than others, and vice-versa.

To add to that, the machines that we would be running these on are CI boxes and there's no guarantee that we're the only job running on those instances, or that the specs are consistent.

I can definitely understand the utility for prospective Ibis users, but it would also be us trying to make ourselves into an arbiter of "which DBMS is the best" and that's not really something we're in a position to do (or do well).


Having said all of that, if there's some other information you're hoping to get out of this comparison run, please let us know and we can think about how to best provide that!

**Comment by cpcloud** [comment]
I think the best alternative to this is https://benchmark.clickhouse.com/.

It has most of the backends we support across a variety of compute specifications.

The main thing we're interested in benchmarking in ibis is any unexpected overhead that ibis itself adds. We do track benchmarks for these kinds of performance issues (though publishing them is currently in limbo after moving to quarto).

Closing as not planned, since ClickBench exists.
