### ISSUE TITLE
docs: add a preamble to the support matrix page

### ISSUE THREAD

**Issue by ianmcook** [ibis-project/ibis#7257]
### Please describe the issue

The operations support matrix page serves as a landing page for visitors looking for more information about Ibis's backends, but it does not explain what a backend is, so visitors who land here are likely to be confused. Add a short preamble at the top explaining this. Copy some of the content from https://ibis-project.org/concepts/backend. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Perhaps we should move it to be less prominent. I'm not convinced it should be a landing page.

**Comment by cpcloud** [comment]
Thinking about the rationale for this, I'm not sure everywhere we mention backends we need to explain what they are.

After all, that is the purpose of the `Concepts` section.

Can we consider other solutions to this problem than duplicating content?

What about making the support matrix page not be the first thing in the list, or removing from that section entirely, so that there's a clean list of only backends.

I think the operation support matrix used to be at the bottom of the list, but it was moved to the top at some point (maybe in the move to Quarto?), perhaps that could also help.

**Comment by ianmcook** [comment]
I think the easiest, cleanest fix is simply to add a brief bit of text (2–3 sentences) at the top of the support matrix page. I don't see any real harm / tradeoff in doing that. Duplicating small bits of content for the purpose of orienting site visitors does not seem harmful. And even if we rejigger links on the Ibis site, visitors will still land on the support matrix page from external links and might be disoriented without a little bit of context about what they're looking at.

**Comment by cpcloud** [comment]
I'm not opposed to content duplication in general, but this issue is making me reconsider the location of the operation support matrix page.

Does it actually need to be so prominent? Is there a better way to orient people than a fairly complex page that requires some knowledge of ibis to be useful?

**Comment by cpcloud** [comment]
To be clear, my comments shouldn't block anything here. Someone should PR the changes (maybe @lostmygithubaccount) and we'll review it.

**Comment by gforsyth** [comment]
I'd say we add the short preamble and drop it to the bottom of the list
