### ISSUE TITLE
Use PyODBC as one of the backend

### ISSUE THREAD

**Issue by adarsh9780** [ibis-project/ibis#7266]
### Is your feature request related to a problem?

I am trying to use Ibis on Windows 10 to query data from Impala server which uses kerberos. I am able to query the server using PyODBC successfully but for some reason Impyla doesn't work on my system. I am not sure why, docs are hard to find. Is there any way we can leverage PyODBC DSN with impala?

### Describe the solution you'd like

I am trying to use Ibis on Windows 10 to query data from Impala server which uses kerberos. I am able to query the server using PyODBC successfully but for some reason Impyla doesn't work on my system. I am not sure why, docs are hard to find. Is there any way we can leverage PyODBC DSN with impala?

### What version of ibis are you running?

2.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Hi @adarsh9780 👋🏻!

Thanks for the issue.

The impala backend is in maintenance-only mode. We aren't taking on any big refactors or feature requests, though we will review related pull requests and fix critical bugs.

It also looks like you're using Ibis 2.0, which we don't have the capacity to support.

Finally, it looks like the issue is about Impala but you wrote that you're using the DuckDB backend. I'm guessing that's just a typo 🙂

I'll add some documentation about Impala support, so that we can set some expectations about what the team is willing to take on.
