### ISSUE TITLE
feat: Consider dropping the how parameter of ops.Correlation  

### ISSUE THREAD

**Issue by mesejo** [ibis-project/ibis#7469]
### Is your feature request related to a problem?

The `how` parameter seems to be ignored in the tests; as proof of the before mentioned, this [implementation](https://github.com/ibis-project/ibis/blob/2d7595511666d6f22ee9c2a99b37ed2e4b60424f/ibis/backends/datafusion/compiler/values.py#L757) is passing both parameters:

```python
@translate_val.register(ops.Correlation)
def correlation(op, *, left, right, where, **_):
    x = op.left
    if x.dtype.is_boolean():
        left = cast(left, dt.float64)

    y = op.right
    if y.dtype.is_boolean():
        right = cast(right, dt.float64)

    return agg["corr"](left, right, where=where)
```

Moreover, several backends do not define the parameter either. In particular, these backends implement only one version of the parameter:

- [DuckDB](https://duckdb.org/docs/sql/aggregates.html#statistical-aggregates)
- [Postgres](https://www.postgresql.org/docs/9.4/functions-aggregate.html)
- [Polars](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.corr.html) (mentions degrees of freedom but no sample or population)
- [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html)implement

### Describe the solution you'd like

Drop the "how" parameter

### What version of ibis are you running?

master

### What backend(s) are you using, if any?

DataFusion

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @mesejo -- thanks for raising this!  

I also find this option a little frustrating.  Currently, Clickhouse and PySpark support _only_ `sample` correlation coefficient, most other backends support only `population` correlation coefs -- I don't know if any backends support both.  That will lead to substantially different answers if someone tries to move an expression between backends that support one vs. the other, and I think that's the kind of BIG difference in results that we want to be explicit about.

If we make a change here, I think it has to remain clear to an end-user that if they switch from e.g. BigQuery to PySpark, things are doing to change beyond just the expected differences due to floating point associativity.
