### ISSUE TITLE
bug: Inconsistent Output on doing the same operation twice

### ISSUE THREAD

**Issue by samlalwani** [ibis-project/ibis#7470]
### What happened?

The following code explains the operation I am trying to perform

1. Read Parquet 

```
t_CN_order = ( ibis.read_parquet(files.CN_order)
                            .distinct(on=['num_DN', 'h3'])
                            .select(['num_DN', 'h3'])
                            .order_by('num_DN'))
```

<img width="107" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/2f6c8f19-147b-44e0-a026-ba4fe0ca80f9">

**Input Table**

2. Drop distinct h3 values from t_CN_order and create t_seq
```
t_seq = (t_CN_order
             .distinct(on='h3')
             .order_by(by=['num_DN', 'h3'])
             .mutate(Hexbin_Sequence_Number=ibis.row_number() + 266)
             .order_by(by=['num_DN', 'Hexbin_Sequence_Number'])
             )
```
<img width="190" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/f1089c27-ade3-4d5c-a735-4ae4f119699f">

**This is an expected output**

3. Repeating the operation above results in different incorrect results
```
t_seq = (t_CN_order
             .distinct(on='h3')
             .order_by(by=['num_DN', 'h3'])
             .mutate(Hexbin_Sequence_Number=ibis.row_number() + 266)
             .order_by(by=['num_DN', 'Hexbin_Sequence_Number'])
             )
```
<img width="190" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/a0194c29-e8b1-4057-a6af-717fbd77fc6a">

**This output is wrong** 
It looks like every time I do this operation again , I am getting a different unpredictable result .

Due to this issue I had to move this operation to pandas to get consistent results.

### What version of ibis are you using?

# Name                    Version                   Build  Channel
ibis-bigquery             7.0.0                hd8ed1ab_1    conda-forge
ibis-duckdb               7.0.0                hd8ed1ab_1    conda-forge
ibis-framework            7.0.0                hd8ed1ab_1    conda-forge
ibis-framework-core       7.0.0              pyhd8ed1ab_1    conda-forge

### What backend(s) are you using, if any?

# Name                    Version                   Build  Channel
duckdb-engine             0.9.2              pyhd8ed1ab_0    conda-forge
ibis-duckdb               7.0.0                hd8ed1ab_1    conda-forge
python-duckdb             0.9.1           py311h12c1d0e_0    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samlalwani** [comment]
Input parquet is attached.
Phillip  , love your youtube channel . Keep up the good work.

Sameer

**Comment by cpcloud** [comment]
@samlalwani Finally had a chance to look into this.

Is there any chance you can elaborate on

> This output is wrong
It looks like every time I do this operation again , I am getting a different unpredictable result .

I understand you're expecting a predictable (perhaps even repeatable?) result. Can you say what you're expecting the result to be?

For example, in

```python
t1 = (
    ibis.read_parquet("/data/CN_order.parquet")
    .distinct(on=["num_DN", "h3"])
    .select(["num_DN", "h3"])
    .order_by("num_DN")
)
```

you're getting results that look different (but aren't equivalent up to but not including row order, per the relational model) because there are repeated values of `num_DN` and you haven't  specified the order of the remaining `h3` column.

Looking at your second query I see 

```python
t2 = (
    t1.distinct(on="h3")
    .order_by(by=["num_DN", "h3"])
    .mutate(Hexbin_Sequence_Number=ibis.row_number() + 266)
    .order_by(by=["num_DN", "Hexbin_Sequence_Number"])
)
```

which has `t1.distinct(on="h3")`.

This will turn into SQL akin to

```sql
SELECT h3, FIRST(capacity), FIRST(dist_m), FIRST(...)
FROM t1
```

The `FIRST` calls **are not deterministically ordered**. This means the "first" value you get for `capacity` won't always be the same value, it depends on the order in which DuckDB processed the row.

I think we might be able to address this, but I'm not sure about a timeline as it's a complex problem to force an ordering for functions like `FIRST` and `LAST` and probably others. There is a way to specify an ordering key in DuckDB's SQL, but it's not really possible to get a determined order for an arbitrary set of rows without assigning every leaf table a hidden row number column which we aren't going to do.

Another thing for us to explore might be to inspect the expression tree and when we see something like

```
Sort(Distinct(on=...))
```

to add the sort keys to the `FIRST` and `LAST` operations we're creating.

That would mean we need a way for aggregation operations to hold sorting keys, which they currently can't.

It's quite a can of worms.

I think your best bet is probably to use `.sql` here.

**Comment by samlalwani** [comment]
@cpcloud 
Let me try to explain the issue with simpler version of code 
```
t_CN_order = (ibis.read_parquet(filename)
                        .select(['num_DN', 'h3'])
                        .distinct(on=['num_DN', 'h3'])
                        .order_by('num_DN') 
                       # .distinct(on=['h3'], keep='first')
                       # .order_by(by=['num_DN'])
            )
```
<img width="171" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/aec5113b-fd45-4e9f-80a9-fffc97d8c9e5">

As expected the num_DN start from 1 and go upto 54

If I uncomment the last 2 lines in the above code

```
t_CN_order = (ibis.read_parquet(filename)
                        .select(['num_DN', 'h3'])
                        .distinct(on=['num_DN', 'h3'])
                        .order_by('num_DN') 
                       .distinct(on=['h3'], keep='first')
                       .order_by(by=['num_DN'])
            )
```

I still expect to get num_DN starting from 1 and going to 54 since I call 
``` 
 .order_by('num_DN')
 .distinct(on=['h3'], keep='first') 
```
Therefore it should respect the order of num_DN but it looks like it ignores num_DN order and keeps distinct h3 rows due to which  the results look like 
<img width="167" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/738ea3b8-47f3-4f0f-980c-57cee6035a30">

As you can see I have lost rows with num_DN from 1 to 29 which had and higher priority over num_DN 30.  It looks like duckdb is ignoring the order before calling distinct.
How do I ensure that distinct uses the order_by specified before it ?

**Comment by samlalwani** [comment]
@cpcloud , Based on the experiments above I realize I have to assume that duckdb is not using the order_by operation before distinct. Hence I cannot trust that output of order_by will flow through.

Thinking bit more about my needs, I realize I can redo this operation in more compact format which is also faster and gives consistent results

```
t_CN_order = ( ibis.read_parquet(filename)                      
                .group_by(by=['h3'])
                .agg(num_DN = _.num_DN.min())                
                .order_by(by=['num_DN'])
            )
```
Which results in the output expected 
<img width="170" alt="image" src="https://github.com/ibis-project/ibis/assets/21284822/97fc8a6f-add7-4160-8e90-e0cb85d06b3c">

**Comment by cpcloud** [comment]
Thanks @samlalwani!
