### ISSUE TITLE
docs: conda-lock file no longer available

### ISSUE THREAD

**Issue by oneextrafact** [ibis-project/ibis#7491]
### Please describe the issue

Docs have a conda/mamba section, but the conda lock file is no longer present. Looks like you folks have added Poetry, which is an awesome development. Can I update the docs to reflect that Poetry has replaced Conda? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
PRs to improve the docs are certainly appreciated! you're referring to this page on the conda tab and lack of the file mentioned? https://ibis-project.org/contribute/01_environment

**Comment by gforsyth** [comment]
Hey @oneextrafact -- I think there's a typo in the path to the conda-lock files, hence the confusion here.  
We use a combination of `poetry` and `poetry2nix` to handle development dependencies for a few of us, but `poetry` by itself (same as `pip` by itself, or `hatch`, or `posy`, or....) isn't quite enough because we have some dependencies that aren't available on PyPI.  The `conda-lock` files live in `ci/conda-lock`
