### ISSUE TITLE
feat: DuckDB read from Azure

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#7493]
looks decently supported now: https://motherduck.com/blog/analyze-data-in-azure-with-duckdb/

**Comment by inigohidalgo** [comment]
Seems to be a more supported implementation than this one which went through adlfs/fsspec, right? https://github.com/duckdb/duckdb/discussions/2565

Will check it out and see if it avoids the problem of slow reads when using wildcards https://github.com/duckdb/duckdb/discussions/2565#discussioncomment-5258966

**Comment by gforsyth** [comment]
Adding the `azure` extension as necessary is fairly straightforward -- the main issue with this, at the moment, is that you need to do a 

```sql
SET azure_storage_connection_string = '<your_connection_string>';
```

Ibis can certainly do this, but it's going to be awkward.  This might be when we need to have a magic dictionary (or something) to simplify setting options in the DuckDB backend.

**Comment by cpcloud** [comment]
(magic dict added by @gforsyth in #7512)

**Comment by gforsyth** [comment]
We're currently blocked on this by the way that the azure-sdk-cpp links in `libcurl` -- their static linking means that we can't connect because the `azure-sdk-cpp` looks for certs in the wrong place (unless you are on windows) and then falls over if it doesn't find them.

The ArcticDB team has gone to the trouble of making this configurable upstream in `azure-sdk-cpp`: https://github.com/Azure/azure-sdk-for-cpp/pull/4982

Once that merged PR is released (still waiting on that), then the DuckDB azure extension can be rebuilt and THEN we'll have the joyous task of allowing users to configure their CERT path to read files from Azure.

Also worth noting that unless we special-case the `azure_storage_connection_string` key in our magic dictionary, users will be met by this charming error message if they try to set it _before_ loading the `azure` extension:
```
ProgrammingError: (duckdb.duckdb.CatalogException) Catalog Error: Setting with name "azure_storage_connection_string" is not in the catalog, but it exists in the azure extension.

Please try installing and loading the azure extension:
INSTALL azure;
LOAD azure;
```

so the gross special-case is to load the `azure` extension if someone tries to set that key.

**Comment by gforsyth** [comment]
Upstream DuckDB azure extension issue: https://github.com/duckdb/duckdb_azure/issues/8
