### ISSUE TITLE
Re-enable partition test after resolution of HIVE-12613

### ISSUE THREAD

**Issue by laserson** [ibis-project/ibis#762]
There is some problem when partitions are dropped.  It is being tracked at HIVE-12613.

**Comment by cpcloud** [comment]
I looked into this a few days ago. I'm able to run the following commands in the `beeline` shell, using the `cpcloud86/impala:metastore` docker image:

Start beeline:

```sh
beeline -n ubuntu -u jdbc:hive2://localhost:10000/default
```

Commands from [HIVE-12613](https://issues.apache.org/jira/browse/HIVE-12613):

```sql
CREATE TABLE foo_partition_test (`foo` string) PARTITIONED BY (`year` int, `month` smallint);
DESCRIBE foo_partition_test;
SHOW PARTITIONS foo_partition_test;
ALTER TABLE foo_partition_test ADD PARTITION (year=2007, month=4) LOCATION '/tmp/tmp-6991f3a5decf47809a513b7007ae6f28';
SHOW PARTITIONS foo_partition_test;
ALTER TABLE foo_partition_test DROP PARTITION (year=2007, month=4);
DROP TABLE foo_partition_test;
```
That HiveQL works for me, but when I try to do it from Ibis, I get the error message described in the Hive issue.
Additionally, if you're logged in as the `impala` user then you can run these commands from ibis.
I think the issue is possibly related to using the `NOSASL` authentication mode, which in `impala.dbapi` doesn't appear to pass the username around. However, it also doesn't look like there's a way to do that with `TSocket` or `TBufferedTransport`.

I'll try to look into this over the weekend to see if it's actually a Hive bug (and try to find a sane workaround) or an Ibis bug that can be fixed.

**Comment by cpcloud** [comment]
Ok, this is related to specifying a specific location for the partition. It looks like if you give a specific path, it *must* be owned by the `impala` user.

We can re-enable the current test (and not specify a specific path for the partition), as well as two additional tests: 1) the current test raises as expected because the `impala` user doesn't necessarily own the `/tmp` directory and 2) a new test that creates a new dir owned by `impala` and makes sure that the `location` parameter works.
