### ISSUE TITLE
timestamp truncation switches 'J' and 'D'

### ISSUE THREAD

**Issue by tsdlovell** [ibis-project/ibis#772]
In a way that probably violates expectations of users of impala and oracle

ibis.impala.compiler._truncate does [this](https://github.com/cloudera/ibis/blob/master/ibis/impala/compiler.py#L946-L947)

``` python
    _impala_unit_names = {
        'M': 'MONTH',
        'D': 'J',
        'J': 'D',
        'H': 'HH'
    }
```

If I execute against an impala client I see

```
In [3]: client.raw_sql('select trunc("2015-01-01 04:00:00", "D")', True).fetchall()
Out[3]: [(datetime.datetime(2014, 12, 29, 0, 0),)]

In [4]: ibis.timestamp("2015-01-01 04:00:00").truncate("D").execute()
Out[4]: Timestamp('2015-01-01 00:00:00')

In [5]: client.raw_sql('select trunc("2015-01-01 04:00:00", "J")', True).fetchall()
Out[5]: [(datetime.datetime(2015, 1, 1, 0, 0),)]

In [6]: ibis.timestamp("2015-01-01 04:00:00").truncate("J").execute()
Out[6]: Timestamp('2014-12-29 00:00:00')
```

**Comment by tsdlovell** [comment]
Incidentally, I prefer ibis' convention since an obtuse shorthand like 'J' seems like it should do something obtuse like 'start of the week' and 'D' should be something straightforward like 'start of the day'.

**Comment by wesm** [comment]
In general, I'd like for the spirit of Ibis to be making sensible decisions around the generic expression API without feeling pressure to conform to legacy issues in the database implementations. Impala uses the Oracle convention probably because of legacy code portability. If it becomes an issue we could always add a compatibility API that behaves like Impala or Oracle.

I marked this for 0.6.1 to make sure the docstrings are clear about what the behavior is.

**Comment by cpcloud** [comment]
These should probably accept some kind of readable constant expression named corresponding to what the underlying string means. Something like:

```python
t.my_timestamp.truncate(ibis.START_OF_DAY)
t.my_timestamp.truncate(ibis.MONTH)
```
These could either be something as simple as the underlying strings themselves or instances of some new kind of expression.

**Comment by cpcloud** [comment]
Closing in favor of #1077
