### ISSUE TITLE
feat: consider: don't pass nulls to python UDFs, or document better

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#7764]
### Is your feature request related to a problem?

In [duckdb UDFs](https://duckdb.org/docs/api/python/function#creating-functions), if an input value is NULL, then the output is always assumed to be NULL, and duckdb never actually calls the python function. Ibis, on the other hand, always calls the python func:

```python
import ibis

ibis.options.interactive = True

t = ibis.memtable({"x": [None, 1]})


@ibis.udf.scalar.python
def my_udf(x: float) -> float:
    assert x is not None


my_udf(t.x) #errors
```

### Describe the solution you'd like

do the same as Duckdb? Otherwise I bet 95% of people's UDFs will need to have `if inp is None: return None` in order to be correct. It seems good to help remove that boilerplate and potential footgun.

However, then this leads to trickiness in consistency with the pyarrow, pandas, and other vectorized APIs, where NULLs are included. I don't think we want to change those semantics, as it would require more complex data slicing.

So perhaps we just leave behavior as is, and just document that this is different from duckdb? But I would rather just do the `if inp is None: return None` check ourselves, I think that will solve more problems than it will create.

### What version of ibis are you running?

7.1.0

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

When I use the exact same input and function as in the DuckDB example I get the equivalent behavior in Ibis:

```
In [1]: import ibis
   ...:
   ...: ibis.options.interactive = True
   ...:
   ...:
   ...: @ibis.udf.scalar.python
   ...: def dont_intercept_null(x: int) -> int:
   ...:     assert x is not None
   ...:     return 5
   ...:
   ...:
   ...: print(dont_intercept_null(None))
   ...:
None

In [2]: print(dont_intercept_null(10))
5
```

The behavior you're seeing is not a generalized problem, but one that is specific to the awful missing value behavior coming from pandas along with some apparent indecisiveness in the DuckDB handling of this admittedly terrible case.

`memtable` constructs a pandas DataFrame by default, whose constructor has no type stability when missing values occur in a non-`double` numeric sequence:

```
In [8]: pd.DataFrame({"x": [None, 1]})
Out[8]:
     x
0  NaN
1  1.0
```

Suddenly your integers are now floats and you've got a NaN instead of a `None`. Wonderful.

When DuckDB calls your function, the NaN is not a `None`, but because `NaN` is used in Pandas to mean NULL DuckDB converts it into a None before passing it to the function.

I'd say this is a DuckDB issue: it should be consistent in its interpretation and conversion (or lack thereof) of NaNs and Nones. Either it's treated as missing and follows the automatic null short circuiting or it's not and the value is passed in unchanged as a NaN.

The other thing to note is that we're not passing in `null_handling="special"`:

https://github.com/ibis-project/ibis/blob/master/ibis/backends/duckdb/__init__.py#L1286-L1292

so there's no obvious way that we'd be triggering the explicit null handling behavior.

**Comment by cpcloud** [comment]
Hm, I just realized I had hacked in using our sqlglot duckdb type when reproducing this which caused it to work 😅 

I'll put up a PR to address that, since without it things break for an unrelated-to-this-issue reason.

**Comment by cpcloud** [comment]
@NickCrews I addressed the underlying issue that you were seeing here inhttps://github.com/ibis-project/ibis/issues/7786!

**Comment by NickCrews** [comment]
Thanks @cpcloud, that new test case looks like it guards against the issue I was seeing!
