### ISSUE TITLE
How to write pandas.DataFrame to HBase backed impala table

### ISSUE THREAD

**Issue by lav-patel** [ibis-project/ibis#779]

**Comment by wesm** [comment]
This is possible but would require a little work to add support for HBase-related DDL statements. My first Kudu integration patch is a good example of the kind of work that would be required: https://github.com/cloudera/ibis/commit/1da1910d5e8ad6fc4b61ec16da19447c01b0cffa . Since we generally don't recommend heavy analytic workloads on HBase it hasn't been as much of a priority
