### ISSUE TITLE
feat(pyodbc+mssql): insert method doesn't accept schema kwarg

### ISSUE THREAD

**Issue by inigohidalgo** [ibis-project/ibis#7794]
### Describe the solution you'd like

The `BaseAlchemyBackend` insert method only accepts a "database" kwarg, whereas I need to provide the schema in the same way I provide it when calling `backend.table`. I saw that depending on the type of `obj`  there is a different branching logic to get the target table, where different methods use different combinations of kwargs for `ops.Namespace`

Ideally I'd like to be able to insert into a table identified by a schema regardless of the origin of the data, if it's a pandas dataframe or another table expression.

### What version of ibis are you running?

8.x.x branch

### What backend(s) are you using, if any?

pyodbc+mssql

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the issue!

This one is going to be a bit of a grind to implement since sqlalchemy has poor support for database -> schema hierarchies.

SQLAlchemy supports one level of hierarchy, but outside of that dialects are left to their own devices to handle namespace. This is one of the many reasons to move away from SQLAlchemy.

We'll probably have to reimplement `insert` just for MS SQL, using sqlglot.

**Comment by gforsyth** [comment]
This is implemented on `main` (although `schema` itself is deprecated) -- you can pass in a two-level hierarchy as `database=("catalog", "database")` or `database="catalog.database"`
