### ISSUE TITLE
feat: bisect method of similar for tracking down where an expression fails

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis#7938]
### Is your feature request related to a problem?

users will often have long and complex Ibis expression, e.g. dozens of joins between tables. an issue within the chain of expressions can be hard to track down

one suggestion is to consider a `.bisect()` method or similar, in place of `to_pandas()`/`execute()`, to help track down where in the expression an error first occurs

### Describe the solution you'd like

something like `expr.bisect()` that will programmatically track down where an error in a large expression occurs and provide useful information in helping to fix it

### What version of ibis are you running?

main

### What backend(s) are you using, if any?

any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jcrist** [comment]
Not +1/-1 on the exact feature, but I'd advocate for this not being a method on `Expr`. Since it's likely to be a rarely used feature and does something kind of "weird", hiding it from the generic `Expr` namespace would seem beneficial to avoiding users accidentally stumbling on it and misusing it. Perhaps `ibis.debug.bisect(expr)` instead? Could put other debug utilities in that namespace as well.

**Comment by lostmygithubaccount** [comment]
no objection from me on the exact semantics, that makes sense
