### ISSUE TITLE
bug: Snowflake insert is not working even for a very simple table

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#7955]
### What happened?

I have following ibis code for snowflake to reproduce the issue
```
import pandas
import ib is
df = pandas.DataFrame.from_dict({"name": ['n1']})
ibis_con = ibis.snowflake.connect(...)
ibis_con.create_table("TEST", schema=ibis.schema([("name", "string")]), overwrite=True)
ibis_con.insert('TEST', df) --> throw exception sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error

# create table with the same df works
ibis_con.create_table("TEST", df, overwrite=True)
```

### What version of ibis are you using?

7.2.0

### What backend(s) are you using, if any?

snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @ruiyang2015, thanks for opening! as a workaround, can you try inserting as an Ibis table instead of a pandas dataframe? and provide more details on the exception?

I was able to insert an Ibis table, but do receive an error about `NAN` values for pandas -- example here: https://gist.github.com/lostmygithubaccount/6535ff05c2f80c8b967fcb6039db05e4
