### ISSUE TITLE
Filtering column fails within groupby

### ISSUE THREAD

**Issue by tdhopper** [ibis-project/ibis#803]
I'm running Ibis 0.7.0 on Python 2.7.11.

I have a `DatabaseTable t` with an integer column called `flags`. I am trying to count how many of the `flags` are greater than 0 within groups, so I ran this:

``` python
aggregates = [t[t.flags > 0].count().name("filtered_size")]
t.group_by('id').aggregate(aggregates).execute()
```

However, the SQL generated by Ibis is 

``` sql
SELECT `id`, count(*) AS `filtered_size` ...
```

The `flags` column isn't mentioned anywhere in the query.

If this behavior should be support, I think there's a bug. If it shouldn't be support, could it throw an exception?

**Comment by tdhopper** [comment]
I see that

```
t.count(where=t.flags > 0)
```

works nicely.

**Comment by wesm** [comment]
Are you hoping for `count(CASE WHEN flags > 0 THEN flags ELSE NULL END)` in the generated SQL or perhaps `count(flags > 0)`? Definitely a bug either way.

Note that `(t.flags > 0).sum()` does what you want, and more pandas-like

**Comment by tdhopper** [comment]
Yeah, `count(CASE WHEN flags > 0 THEN flags ELSE NULL END)` is what I was expecting. I didn't think about the `sum()` option, but that's great.

**Comment by cpcloud** [comment]
What's the bug here? This is now raising a sensible error, indicating that the source relation of the aggregation is not the same as the source relation of the rest of the expression.

**Comment by wesm** [comment]
For now, I think this should throw an exception. It would be nice (for usability) to be able to have `t[boolean_cond].count()` auto translate to `t.count(where=boolean_cond)`. I may actually have an issue already for this

**Comment by cpcloud** [comment]
Is there a mechanism for rewriting expressions *before* predicates and columns in the select are separated. I played around with this but it looks like rewrites are happening after the predicates are removed from the aggregate.

**Comment by wesm** [comment]
It seems like this analysis/expr-transformation would have to happen when the aggregate operation is formed

**Comment by cpcloud** [comment]
Thinking about this a bit. I don't think we should pull predicates that filter data into aggregates. Even though the results are often the same between filtering in the `WHERE` clauses versus putting the filter in the aggregation function, I don't think in general it's possible to tell when this matters to the database. For example, often you'll want to pick a single day's data and count things from there like so:

```sql
SELECT
  COUNT(1) FILTER (WHERE some_column > 0) AS filtered
FROM t
WHERE "date" = DATE(TODAY())
```

versus

```sql
SELECT
  COUNT(1) FILTER (
    WHERE "date" = DATE(TODAY()) AND some_column > 0
  ) AS filtered
FROM t
```

In the HDFS world, tables are partitioned on some column and filtering on that column greatly improves performance since you're reducing the amount of data queried.

If we go the route of pulling up filters into aggregates, we're implicitly assuming that the database knows how to prune partitions in aggregates. I'm not sure if this assumption is reasonable or not, but since there's an alternative way of doing this that doesn't require this assumption I'm -1 on automatically pulling predicates from the where clause into a filter on an aggregate.

**Comment by cpcloud** [comment]
I'm going to remove the bug marker here. It's not clear that this is actually a bug, or just something that needs to be better documented. @wesm @tdhopper Please comment if you feel otherwise.

**Comment by cpcloud** [comment]
Closing.
