### ISSUE TITLE
feat: support fsspec for read_csv/json/parquet for all backend

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#8039]
### Is your feature request related to a problem?

currently ibis.duckdb support not only read_csv from a path, but it can also register a fsspec object which can support either s3fs/gcsfs/abfs/sftpfs ...
I would like all the backend support such feature, especially for BigQuery and Snowflake.

### Describe the solution you'd like

I would like ibis.read_csv|read_json|read_parquet can either take a path string or fsspec FileSystem object.

### What version of ibis are you running?

7.2.0

### What backend(s) are you using, if any?

BigQuery, Snowflake

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gforsyth** [comment]
Hey @ruiyang2015 -- the DuckDB backend supports reading from `fsspec` because DuckDB itself has support for reading from `fsspec`.  We try to avoid handling IO on the Ibis side, especially for the cloud backends, as it makes Ibis a choke point and slows down reading in data. 

If BigQuery or Snowflake add native support for reading from `fsspec` objects, then we can certainly expose that functionality, but until then, we're limited by what the backend can do.  I'm going to close this out for now, but please ping if there are developments on the Bigquery or Snowflake side.  Thanks!
