### ISSUE TITLE
bug: Geospatial blogpost broken on `the-epic-split`

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#8145]
### What happened?

I tried to run the code in this geospatial blog https://ibis-project.org/posts/ibis-duckdb-geospatial/ using `the-epic-split` branch and run into a problem. 

Reproducible example (find a simpler one in comment below)
```python
# Get data

from pathlib import Path
from zipfile import ZipFile
from urllib.request import urlretrieve

# Download and unzip
url = "https://open.gishub.org/data/duckdb/nyc_data.db.zip"
zip_path = Path("nyc_data.db.zip")
db_path = Path("nyc_data.db")

if not zip_path.exists():
    urlretrieve(url, zip_path)

if not db_path.exists():
    with ZipFile(zip_path) as zip_file:
        zip_file.extract("nyc_data.db")
        
import ibis
from ibis import _

ibis.options.interactive = True

con = ibis.duckdb.connect("nyc_data.db")

subway_stations = con.table("nyc_subway_stations")
subway_stations.filter(_.geom.geo_equals(_.filter(_.NAME == "Broad St").geom))
```
The error is long, but the last part is 
```python-traceback
...ibis/ibis/backends/duckdb/__init__.py:107, in Backend.raw_sql(self, query, **kwargs)
    105 with contextlib.suppress(AttributeError):
    106     query = query.sql(dialect=self.name)
--> 107 return self.con.execute(query, **kwargs)

BinderException: Binder Error: Referenced table "t1" not found!
Candidate tables: "t0"
```

### What version of ibis are you using?

`the-epic-split`

### What backend(s) are you using, if any?

duckdb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
After a chat with the team, @cpcloud mentioned that the issue might be somewhere in the `merge_select_select` https://github.com/ibis-project/ibis/blob/e68000c06673fd4eaa0644dac869fae75f6b0ce5/ibis/backends/base/sqlglot/rewrites.py#L117-L146 

I'm not quite sure how to tackle this, but I found a better reproducer using the penguins example, it's kind of dumb but I think it triggers the same path. 

```python
from ibis.interactive import *
t = ibis.examples.penguins.fetch()

f1 = t.filter(t.bill_depth_mm==14.9)
t.filter(t.bill_depth_mm==f1.bill_depth_mm)
```
```python-traceback
BinderException: Binder Error: Referenced table "t1" not found!
Candidate tables: "t0"
```

cc: @cpcloud and @kszucs (Phillip mentioned you'll be interested in this)

**Comment by kszucs** [comment]
The repr of the expression above is the following:

```
r0 := DatabaseTable: penguins
  species           string
  island            string
  bill_length_mm    float64
  bill_depth_mm     float64
  flipper_length_mm int64
  body_mass_g       int64
  sex               string
  year              int64

r1 := Filter[r0]
  r0.bill_depth_mm == 14.9

Filter[r0]
  r0.bill_depth_mm == r1.bill_depth_mm
```

Note that the `Filter` node references two relations. We allow the other relation in the `Filter` predicate so that we can implement correlated subqueries. Since we allow it in the IR the expression can be compiled to SQL:

```sql
SELECT
  "t0"."species",
  "t0"."island",
  "t0"."bill_length_mm",
  "t0"."bill_depth_mm",
  "t0"."flipper_length_mm",
  "t0"."body_mass_g",
  "t0"."sex",
  "t0"."year"
FROM "penguins" AS "t0"
WHERE
  "t0"."bill_depth_mm" = "t1"."bill_depth_mm"
```

Raising an error at this point is hard because we cannot know whether the filter is going to be used in a subquery or not. However we could raise during the application of the SQL rewrites, but this problem applies to all backends actually so we should handle it uniformly. 

Another option could be dereference `f1.bill_depth_mm` to `14.9`, but I'm not sure whether that is desirable since it can be confusing.

**Comment by ncclementi** [comment]
Just to be clear, this currently works on main. Here is another example, which is more realistic, that triggers the same. But in this case we have two different tables (fyi, this also works on on main)

```python
import ibis
ibis.options.interactive = True
con = ibis.duckdb.connect("nyc_data.db")

subway_stations = con.table("nyc_subway_stations")
boroughs = con.table("nyc_neighborhoods")

boroughs.filter(_.geom.intersects(subway_stations.filter(_.NAME == "Broad St").geom))
```

```python-traceback
BinderException: Binder Error: Referenced table "t2" not found!
Candidate tables: "t0"
```

**Comment by kszucs** [comment]
The main issue here is that `subway_stations.filter(_.NAME == "Broad St")` is not guaranteed to return a single row, so the expression's validity depends on the data stored in the backend. On the other hand calling `.limit(1)` on it would ensure that the resultset has a single row in it. 

Even if we keep the behaviour in `main` it is tricky to turn the nested filters into scalar subqueries since we cannot know whether the expression is going to be used a correlated subquery or not.

**Comment by cpcloud** [comment]
Closed by https://github.com/ibis-project/ibis/pull/8227

**Comment by kszucs** [comment]
Note that I still need to fix the subquery validation/coercion.
