### ISSUE TITLE
bug: `from ibis.interactive import *` does not work on docstrigns examples

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/ibis#8147]
### What happened?

When creating the examples in docstrings, using `from ibis.interactive import *` does not seem to trigger interactivity. See this CI failure for reference https://github.com/ibis-project/ibis/actions/runs/7704134342/job/20995864530?pr=8128

### What version of ibis are you using?

Ibis main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This is due to module caching. Running `from ibis.interactive import *` will not run the code in `ibis.interactive` more than once, without resorting to `sys.modules` hacking or `importlib.reload`. Doing either one of those things just to allow `from ibis.interactive import *` seems like a lot of code/effort for something that we can do by setting a flag.
