### ISSUE TITLE
bug(bigquery):  Numeric precision increase 1 unexpectedly after every sub/add operations

### ISSUE THREAD

**Issue by chelsea-lin** [ibis-project/ibis#8189]
### What happened?

The numeric precision get automacially increase 1 per sub/add operations unexpectedly, though BQ only supports `precision=38` for `NUMERIC` and `precision=76` for `BIGNUMERIC`.

The code to repro the issue:

```
>>> import ibis
>>> bq = ibis.bigquery.connect(project_id="bigframes-dev")
>>> taxi_dt = bq.table("bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022")
>>> taxi_dt['trip_distance'].type()
Decimal(precision=38, scale=9, nullable=True)
>>> result = taxi_dt['trip_distance']+taxi_dt['trip_distance']
>>> result.type()
Decimal(precision=39, scale=9, nullable=True)
```
The expected `result.type()` would be `Decimal(precision=38, scale=9, nullable=True)`

### What version of ibis are you using?

7.1.0

### What backend(s) are you using, if any?

BigQuery

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chelsea-lin** [comment]
The [_promote_decimal_binop](https://github.com/ibis-project/ibis/blob/8e190bb70c36b83828906a142f34a8d285aca518/ibis/expr/rules.py#L111) function auto increases the decimal for binop. I tried to check if the `left.arg.table.source.db_identity` is `bigquery.Backend` in this function. However, this will introduce the circular import (ibis/backends -> ibis/expr -> ibis/backends). 
Any other potential solution to fix the issue here?

**Comment by tswast** [comment]
The decimal type evolution introduced to fix https://github.com/ibis-project/ibis/issues/4319 for DB2 is inconsistent with how types evolve in BigQuery, which follows these rules: https://cloud.google.com/bigquery/docs/reference/standard-sql/operators#arithmetic_operators

In BigQuery DataFrames, we rely on the type of the Ibis expression to (1) determine which pandas type we're emulating and (2) in our I/O, when we actually execute the query we don't actually do .execute() so that we have a little more control over how the query is run. In both of these steps, we expect there to be a pretty constant mapping from ibis type to BigQuery type. For example, here's one of our mappings for (1) https://github.com/googleapis/python-bigquery-dataframes/blob/b90241e6db8fa7b5dce29c5fc5e0d6d81d6595e6/bigframes/dtypes.py#L110-L131
