### ISSUE TITLE
feat: `ibis.from_*` methods for injesting in-memory data structures

### ISSUE THREAD

**Issue by jcrist** [ibis-project/ibis#8622]
One API choice I've thought about is adding (or maybe switching to) `ibis.from_*` functions like `ibis.from_pandas`/`ibis.from_polars`/`ibis.from_pyarrow`. Implementation-wise this would be similar to our existing `ibis.memtable` function, the only real difference is in spelling.

**Pros**
- These are a bit more discoverable and clearly named than `ibis.memtable`. Users doing tab-completion-driven-development can see all the in-memory formats that can be injested by `ibis` explicitly as their API names.
- There's a nice symmetry between the `from_*` methods and the `to_*` methods, as they both support similar formats.
- These naturally extend to both columns and tables (as per the request in #8621).
- To a user the output of `ibis.memtable` should be indistinguishable from any other table in ibis. Calling the intake function "memtable" feels like it's creating a named concept where there doesn't need to be one.

**Cons**
- Sometimes you might want a mega-function like `ibis.memtable` that takes some in-memory structure and spits out an ibis table. This is similar to the `ibis.connect` URL-based API and the `ibis.{backend}.connect` backend-specific APIs.

**Comment by NickCrews** [comment]
There are two concepts of the API here:
- what is the output shape?
    - Scalar (already have ibis.literal(), ibis.map(), etc)
    - Column
    - Table (already have ibis.memtable())
 - What is the input format?
     - python literals
     - pandas
     - pyarrow
     - polars

If we went with .from_pandas() etc, then we are making the input format explicit, but the output shape implicit (I need to know if I am passing in a pd.Series vs pd.DataFrame). I would rather have this be the other way around: the output shape explicit, but I don't really care what the input I'm putting in.

I agree `memtable` is a sorta bad name. Could we be really breaking and merge this with the existing `ibis.table()`, so that function can either have bound data, or not? Then we would have
- ibis.table(data, schema=None, name=None)
- ibis.column(data, type=None, name=None) (maybe)
- ibis.literal(data, type=None)
That is a very nice consistent factory API in my opinion.

**Comment by cpcloud** [comment]
I think `ibis.column` is probably a non-starter. A column must always be attached to a table and presumably you'd eventually want to combine this naked column with a table in some way.

@NickCrews How are you thinking you'd use `ibis.column`?

**Comment by contang0** [comment]
As a user I like ibis.memtable. I personally like seeing less methods to think about. When I call memtable on some dataframe (be it pandas or whichever), I just assume that ibis knows how to handle it. I would not prefer to do dir(ibis) just to check if Ibis has that particular from_* method. But that's just me!

**Comment by NickCrews** [comment]
I have functions that take a column and return one or more columns (see https://github.com/ibis-project/ibis/issues/8484), and for unit testing it would be cleaner.

Or for doing set operations, like removing stop words like "street" "avenue" etc from a table, I think the most efficient way is with an antijoin, so i specify the stop words in a column.

Neither of these are huge pain points though I will say.

**Comment by ncclementi** [comment]
closing in favor of #6593
