### ISSUE TITLE
bug: flink isn't installed in local dev env

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8696]
### What happened?

As I worked on https://github.com/ibis-project/ibis/pull/8648 I was getting flink failures in CI. Whenever I tried running the tests locally with `pytest -m flink -v ibis/backends/tests/test_map.py`, then I would get `SKIPPED (could not import 'pyflink': No module named 'pyflink')`

I installed via `python -m pip install -r requirements-dev.txt` and then `python -m pip install -e .` (is the `.[all]` needed to get flink?), but pyflink isn't in there. flink needs to get added somewhere so it appears in this lockfile? If I manually `python -m pip install 'apache-flink'` then those tests actually run.

I am on an M1 mac, macOS 14.1.1 (23B81).

### What version of ibis are you using?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NickCrews** [comment]
Duplicate of https://github.com/ibis-project/ibis/pull/8544

**Comment by gforsyth** [comment]
Hey @NickCrews -- for a full development environment we strongly recommend using either `conda` or `nix`.

@ncclementi did the thankless job of figuring out the right conda environment file for a flink-enabled dev environment on an M1 that lives in conda/environment-arm64-flink.yml

The reason we currently aren't including the `pyflink` extra is because of the transitional dependency on `apache-beam` which itself has a (quite old) upper bound on `pyarrow`.

**Comment by NickCrews** [comment]
Gotcha thanks for the background!

I will try that conda env. I tried the nix setup and that didn't work on my m1 FYI

**Comment by gforsyth** [comment]
> I will try that conda env. I tried the nix setup and that didn't work on my m1 FYI

I know it's _possible_ to use nix on an M1 but neither I nor @cpcloud have one to mess around with.  If you _do_ get it working, please let us know and we can get some better instructions added to the dev docs.

**Comment by lostmygithubaccount** [comment]
I have also tried nix on m1/m2 and it didn't go well. I personally just use pip and deal with things but +1 on conda for ease of installation on a mac

**Comment by cpcloud** [comment]
I worked on getting nix working with m1 using a cloud macos instance, and I got most of it working but gave up when it turned out I need two versions of Cython to build the environment, because PyYAML doesn't support Cython 3 and nix **enforces** that you have a single version of a given Python package in an environment.

Maybe we'll get there someday!
