### ISSUE TITLE
feat: increase `ibis.options.repr.interactive.max_length` from 2 to 3

### ISSUE THREAD

**Issue by NickCrews** [ibis-project/ibis#8765]
### Is your feature request related to a problem?

it is annoying how If I have a simple `ibis.array([1,2,3])`, the repr is `[1, 2, ... +1]`. Several doctests that use arrays aren't as clear as they could be because of this.

I'm not exactly sure the history here, perhaps there is a good reason for the current value.

### Describe the solution you'd like

increase it to 3

### What version of ibis are you running?

main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I agree, it's annoying. It was introduced at the same time as the rich repr was introduced (https://github.com/ibis-project/ibis/pull/4471).

The reason that I did this was that the election 2020 dataset I was testing against (which is a dataset I collected during the 2020 US presidential election, it's not public) has some of the worst (or best, depending on your perspective) nesting I've ever seen, likely because I was just dumping JSON responses from the New York Times election data API into a file as the election was happening.

That dataset is so deeply nested that showing more than two elements of one of its arrays caused the repr to be so so that it was unusable. I use this dataset as a sort of benchmark for any tools that come along claiming to handle nested data.

For reference, each **row** of this dataset is about 10 MB of JSON. The nesting is outrageous.

That dataset is also in all likelihood an outlier, so we could potentially change it I guess.

**Comment by cpcloud** [comment]
If making the docstrings more clear is what you're after, we can do that without changing the default. The trade off there is that when people run it in their terminal they won't have enabled the setting and thus it won't look like it does in the docs.

**Comment by NickCrews** [comment]
Thanks, that case is good to be aware of. If that case is an outlier though, then why not make that case be the one that has to do extra effort and reduce the `max_length` from 3 to 2, instead of making the common case do the effort? If we did this, we may want to add a warning or something that says "rendering is taking a long time, consider doing....", or I could see it not being very obvious what the cause of the slowdown is.

Or, this would be a separate direction, where we could add some counter to our repr code, and if we recurse into some value say 10+ times then we stop. That would be an option orthogonal to max_length, max_depth, etc. Or maybe upstream that into rich itself.

**Comment by cpcloud** [comment]
There's no recursing that we're doing there, it's all happening in rich

**Comment by NickCrews** [comment]
It looks like originally you had [max_depth defaulting to 2](https://github.com/ibis-project/ibis/pull/4471/files#diff-0f9cc26677da8931e7536cb28b981ad29623420291ee197ad5f4d3eaa217793aR91), but that quickly [got decreased to 1](https://github.com/ibis-project/ibis/commit/522db9c646850f6245ae770400d14ac731bbcee2#diff-0f9cc26677da8931e7536cb28b981ad29623420291ee197ad5f4d3eaa217793aR94). So I think the actually the edge case shouldn't be a problem now, and we could increase max_length safely?

**Comment by cpcloud** [comment]
`gs://ibis-debugging/election2020_single_chunk.jsonl` is the GCS URI for the JSON version which DuckDB should be able to read (this particular chunk was used by one of the DuckDB folks to help debug JSON type inference).

**Comment by cpcloud** [comment]
Trying it out locally, the repr is still pretty slow to show the first 10 rows:

```
In [5]: %time r = repr(t)
CPU times: user 15.8 s, sys: 2.21 s, total: 18 s
Wall time: 15.9 s
```

**Comment by NickCrews** [comment]
`ibis.read_json("gs://ibis-debugging/election2020_single_chunk.jsonl")` gives me a 404, do I need creds?

**Comment by cpcloud** [comment]
You need the http URL for that: `https://storage.googleapis.com/ibis-debugging/election2020_single_chunk.jsonl`

**Comment by cpcloud** [comment]
The repr will be ridiculously slow pulling 200 MB of JSON over http, so I'd suggest you cache it if you're going to iterate on the settings.

**Comment by cpcloud** [comment]
I guess the performance isn't snappy no matter what the nesting level is, but with greater `max_level` and `max_length`, the table becomes unreadable.

**Comment by cpcloud** [comment]
For posterity, if the URL were visible but you didn't have access, ideally that would result in a 403 (forbidden).

**Comment by cpcloud** [comment]
Closing this out as stale.
