### ISSUE TITLE
feat: add databricks support

### ISSUE THREAD

**Issue by ruiyang2015** [ibis-project/ibis#9248]
### Which new backend would you like to see in Ibis?

I would like to see databricks backend support.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
@ruiyang2015 Can you clarify a bit what "databricks" means here? Is that databricks cloud, databricks connect, or something else?

**Comment by ruiyang2015** [comment]
> @ruiyang2015 Can you clarify a bit what "databricks" means here? Is that databricks cloud, databricks connect, or something else?

We use databricks connect and databricks SQL endpoints.

**Comment by Kilo59** [comment]
https://docs.databricks.com/en/sql/language-manual/index.html
https://github.com/databricks/databricks-sql-python

**Comment by cpcloud** [comment]
@Kilo59 Thanks for the links! The databricks DB-API looks pretty solid. They even support fetching query results as arrow tables.

**Comment by techdebtcreator** [comment]
+1 for this since my company mainly uses Databricks SQL Warehouse via the `databricks-sql-connector` package. Unless I missed something, I'm currently only able to connect to Databricks clusters (through the Ibis PySpark backend in conjunction with the `databricks-connect` package).

**Comment by nrlugg** [comment]
For reference, there is also the [`databricks-sdk`](https://databricks-sdk-py.readthedocs.io/en/latest/) package which could also be used for querying Databricks SQL Warehouses using the [`statement_execution`](https://databricks-sdk-py.readthedocs.io/en/latest/workspace/sql/statement_execution.html) submodule.

This package is particularly interesting because, if you use `format=Format.ARROW_STREAM` and `disposition=Disposition.EXTERNAL_LINKS`, it allows streaming chunks of serialized arrow tables (i.e., arrow IPC format), and this could potentially be used for processing tables which are larger than memory and/or be read using asynchronous calls or multi-threading to stream the data faster.

**Comment by hershelm** [comment]
+1 would be great to see native support for databricks

anyone in the thread, may find this blog post useful: https://posit.co/blog/databases-with-posit/

see the section on "Databricks" and the "Python" tab

**Comment by cpcloud** [comment]
We will be tackling this for the 10.0 release, stay tuned!

**Comment by deepyaman** [comment]
> To answer your direct question, yes. My main goal of the PR for me would be to make working with pyspark in databricks easier. 

_Originally posted by @mark-druffel in https://github.com/kedro-org/kedro-plugins/issues/833#issuecomment-2430486118_

@mark-druffel I'm guessing you'll be interested in this (and #10223), if you haven't seen them already!
