### ISSUE TITLE
bug: Loading geometry from postgres with SRID gives error

### ISSUE THREAD

**Issue by Riezebos** [ibis-project/ibis#9465]
### What happened?

Very similar to #8807. When trying to load a table with a geometry that has an SRID set, I get the following error:

`TypeError: SqlglotType._from_sqlglot_GEOMETRY() takes from 1 to 2 positional arguments but 3 were given`

Here is a reproducible example:

```sql
drop table if exists v_test;
CREATE TABLE v_test (
    id int8 NULL,
    lonlat geometry(Point, 4326) NULL
);

INSERT INTO v_test (id, lonlat)
VALUES 
    (2, st_setsrid(st_makepoint(5.7, 53.2),4326));
```

```python
import ibis

ibis.options.interactive = True

pg_con = ibis.connect(
    "postgresql://blablabla",
)

pg_con.sql("select * from v_test").execute()
```

If it helps, loading this table with geopandas does not give errors.

### What version of ibis are you using?

ibis-framework[postgres,geospatial]==9.1.0

(Also tried --pre)

### What backend(s) are you using, if any?

Postgres

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ncclementi** [comment]
@Riezebos thank you for reporting this. I think I know where the problem is, but I need to investigate a bit more.

@cpcloud looks like the tests that we have checking if `srid` work is not catching this problem. 
I'm not sure I follow exactly, why...
https://github.com/ibis-project/ibis/blob/5a9d0263addcd53897cc15b2c1ad952353640a2c/ibis/backends/postgres/tests/test_geospatial.py#L247-L262

Looks, it's failing here, because there is no way to pass the srid at this stage, however I don't see any references in the code to this method, so I'm not sure how we get there. Do you have any clues?

https://github.com/ibis-project/ibis/blob/5a9d0263addcd53897cc15b2c1ad952353640a2c/ibis/backends/sql/datatypes.py#L298-L304

**Comment by cpcloud** [comment]
From triage earlier today: from the `TypeError` in the initial report, this likely is us not threading the second parameter (that contains the SRID) through our sqlglot -> ibis type converter.

**Comment by cpcloud** [comment]
Would be nice to get this in for 9.2!
