### ISSUE TITLE
bug: categorical column from Polars incorrectly noted as DtypeKind.STRING

### ISSUE THREAD

**Issue by MarcoGorelli** [ibis-project/ibis#9570]
### What happened?

```python
df = pl.DataFrame({ "a": ["fdafsd", "fdas", "ad"] }, schema={'a': pl.Categorical})
print(df.__dataframe__().get_column_by_name('a').dtype)
print(ibis.memtable(df).__dataframe__().get_column_by_name('a').dtype)
```

outputs
```
(<DtypeKind.CATEGORICAL: 23>, 32, 'I', '=')
(<DtypeKind.STRING: 21>, 8, 'u', '=')
```

(noticed while trying to add initial Ibis support [here](https://github.com/narwhals-dev/narwhals/issues/388))

### What version of ibis are you using?

9.1.0

### What backend(s) are you using, if any?

polars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Ibis doesn't have a categorical type, so we map those to the underlying element type. We used to have a categorical type, but it has pretty limited utility in the context of Ibis, because it's an implementation detail of the physical representation and AFAIK has no bearing on what operations are available.

**Comment by MarcoGorelli** [comment]
thanks @cpcloud ! closing then as it sounds like expected behaviour
