### ISSUE TITLE
bug: read_parquet mangles huggingface prefix

### ISSUE THREAD

**Issue by cboettig** [ibis-project/ibis#9689]
### What happened?

duckdb supports reading data directly from huggingface!  https://duckdb.org/2024/05/29/access-150k-plus-datasets-from-hugging-face-with-duckdb.html

But `read_parquet()` in ibis doesn't recognize the `hf://` prefix, and decides that it must be some kind of local file path.  

### What version of ibis are you using?

9.10

### What backend(s) are you using, if any?

DuckDB!

### Relevant log output

```python
parquet = "hf://datasets/boettiger-lab/gbif/usa_h3/*/*.parquet"
df = con.read_parquet(parquet)
```

```
FileNotFoundError: /home/rstudio/huggingface/spaces/gbif/hf:/datasets/boettiger-lab/gbif/usa_h3/*.parquet
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
I suspect that we should probably avoid hard-coding the list of ignored prefixes, which we are using so that we can turn files into absolute paths, but I don't think that's necessary either.

I'll remove the hardcoded list, which allows `hf` and any other prefix someone comes up with to work, and see what breaks.
