### ISSUE TITLE
bug: Deferred doesn't work when combining selectors.across with ArrayColumn.map

### ISSUE THREAD

**Issue by Riezebos** [ibis-project/ibis#9705]
### What happened?

In the examples of Array.map, _ is used to refer to values of the array. In the examples of s.across, _ is used to refer to each column. It seems that when combining the two, _ still refers to the column within `.map` instead of referring to each array value.

```python
import ibis
from ibis import _
from ibis import selectors as s

ibis.options.interactive = True

t = ibis.memtable(
    {
        "a": [["a", "b", "c"], ["c", "d", "e"]],
        "b": [1, 2],
    }
)

t.mutate(s.across(s.of_type(ibis.dtype("array<string>")), _.map(_.upper())))
```

Output:
```
AttributeError: 'ArrayColumn' object has no attribute 'upper'
```

I was able to work around it by using a lambda function in `.map` instead of the deferred expression, but I would imagine the above is supposed to work, so I thought I'd report it.

References:
- https://ibis-project.org/reference/expression-collections#ibis.expr.types.arrays.ArrayValue.map
- https://ibis-project.org/reference/selectors.html#ibis.selectors.across

### What version of ibis are you using?

9.2.0

### What backend(s) are you using, if any?

DuckDB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
This working as intended. The meaning of `_` never changes for a given function/method call. It's always either "the most recently created table expression" or in the special case of `across`, the column to apply the transformation to.

Your example would combine those semantics, and we intentionally currently don't support that because of the technical complexity required to, as well as the different interpretations it might lend itself to.
