### ISSUE TITLE
feat: pandas backend cannot use sql, can you add this?

### ISSUE THREAD

**Issue by 332123342** [ibis-project/ibis#9806]
### Describe the solution you'd like

like this
```
import ibis
import pandas as pd

ibis.options.interactive = True
df = pd.DataFrame(
    [["a", 1, 2], ["b", 3, 4]],
    columns=["one", "two", "three"],
    index=[5, 6],
)
con = ibis.pandas.connect({'df': df})
t = con.table('df')
a = con.sql("SELECT count(*) AS count FROM df")
```

### What version of ibis are you running?

9.3.0

### What backend(s) are you using, if any?

pandas

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostmygithubaccount** [comment]
hi @332123342, thanks for opening! in short, pandas does not support SQL so this isn't something Ibis will add on top of it. it could technically be feasible, but we don't see much value in the pandas backend

is there any particular reason you are using the pandas backend instead of something like DuckDB, which does support SQL and effectively all operations the pandas backend supports? we are considering removing the pandas backend in favor of DuckDB

**Comment by cpcloud** [comment]
We are not going to add SQL support for the pandas backend, so I'm going to close this out.

Happy to discuss alternative solutions to querying pandas DataFrames with SQL though.

Our DuckDB backend is the best alternative and in some cases is actually faster than pandas itself.
